import { BootcampTrack } from "./bootcamp-data";

/**
 * 31 Industrial Engineering Tracks covering all requested domains & subdomains.
 * Includes the 100% Free Testing Sandbox Track for instant verification.
 */
export const EXTENDED_BOOTCAMP_TRACKS: BootcampTrack[] = [
  // 0. FREE TEST COURSE & TESTING TRACK
  {
    id: "developer-sandbox",
    slug: "developer-sandbox",
    title: "Developer Zero: Interactive Architecture & Git Sandbox (Free Test Track)",
    domain: "Developer Onboarding & Hands-On Testing",
    category: "FREE_TEST",
    icon: "🚀",
    badge: "100% FREE TEST TRACK",
    durationWeeks: 4,
    totalHours: 160,
    pricing: {
      originalPrice: 0,
      discountedPrice: 0,
      currency: "INR",
    },
    tagline: "Free interactive test track to explore and test the RoleNest Internship & Course ecosystem with zero payment.",
    overview:
      "A complete hands-on sandbox curriculum designed to test the entire industrial virtual internship experience: instant free registration, automated Offer Letter issuance, college NOC generation, in-browser Code Arena execution, and cryptographic certificate verification.",
    targetAudience: [
      "Candidates and evaluators testing the RoleNest Virtual Labs platform",
      "Engineering students wanting a zero-cost interactive test drive",
      "Developers learning foundational git, terminal pipelines, and clean architecture",
    ],
    prerequisites: [
      "Any modern web browser",
      "Curiosity to explore full-stack development and testing workflows",
    ],
    discordChannel: "#free-testing-sandbox",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "100% Instant Approval with Downloadable Verification Letter",
    },
    certificateSpec: {
      prefix: "RN-INT-SANDBOX",
      title: "Interactive Full-Stack Architecture & Git Sandbox Specialist",
      designation: "Certified Software Engineer (Testing Cohort)",
      skills: ["Git Workflows", "Terminal Primitives", "Clean Architecture", "Unit Testing", "CI/CD Basics", "Open Source"],
    },
    weeks: [
      {
        weekNumber: 1,
        title: "Developer Foundations & Git Plumbing Internals",
        theme: "Environment Setup, Version Control & Terminal Literacy",
        hours: 40,
        description: "Explore the internals of Git, blob/tree/commit objects, branching strategies, and terminal debugging.",
        coreTopics: ["Git Object Model", "Interactive Rebase", "Commit Signing", "Terminal Command Chaining"],
        practicalLabs: ["Inspect .git/objects", "Resolve complex merge conflicts", "Build an automated bash pipeline"],
        weeklyProject: {
          name: "Interactive CLI Task Orchestrator",
          deliverable: "GitHub repository with automated unit tests and README",
          techStack: ["Node.js / Python", "Git", "Markdown"],
        },
        studyMaterial: {
          title: "Week 1 Blueprint: Git Internals & Developer Tooling",
          filename: "Sandbox_Week1_Git_Internals.pdf",
          totalPages: 24,
          downloadUrl: "/downloads/sample-guide.pdf",
          summary: "Comprehensive architectural guide to Git internals, SHA hashes, and terminal workflows.",
          topicsCovered: ["Git DAG", "Plumbing vs Porcelain", "Clean Commits"],
          keyTakeaways: ["Understand Git as a content-addressable database", "Create pristine PRs"],
        },
      },
      {
        weekNumber: 2,
        title: "Modular Clean Architecture & REST API Testing",
        theme: "System Layering, Domain Models & Test Suites",
        hours: 40,
        description: "Architect loosely coupled software modules, implement unit and integration tests, and validate API endpoints.",
        coreTopics: ["Clean Architecture", "Dependency Injection", "API Contracts", "Automated Testing"],
        practicalLabs: ["Build CRUD handlers with schema validation", "Write mock test suites with >90% coverage"],
        weeklyProject: {
          name: "Resilient Micro-Service Mock with Health Checks",
          deliverable: "Tested service with automated GitHub Actions workflow",
          techStack: ["TypeScript / Python", "Jest / PyTest"],
        },
        studyMaterial: {
          title: "Week 2 Blueprint: Software Modularity & Testing Strategies",
          filename: "Sandbox_Week2_Testing.pdf",
          totalPages: 28,
          downloadUrl: "/downloads/sample-guide.pdf",
          summary: "Guide to writing maintainable code and testing distributed endpoints.",
          topicsCovered: ["TDD Basics", "Mocking Dependencies", "Edge Cases"],
          keyTakeaways: ["Eliminate flaky tests", "Deliver production quality code"],
        },
      },
      {
        weekNumber: 3,
        title: "Database Modeling, Indexing & High-Performance Caching",
        theme: "Persistence, Relational Schemas & Redis Caches",
        hours: 40,
        description: "Design relational models, optimize SQL joins, and implement sub-millisecond Redis caching layers.",
        coreTopics: ["Relational Schemas", "B-Tree Indexes", "Cache-Aside Pattern", "Transaction Isolation"],
        practicalLabs: ["Analyze EXPLAIN ANALYZE execution plans", "Configure Redis cache invalidation"],
        weeklyProject: {
          name: "High-Throughput Cached Data Store",
          deliverable: "Benchmarked database schema with stress test reports",
          techStack: ["PostgreSQL / SQLite", "Redis", "Docker"],
        },
        studyMaterial: {
          title: "Week 3 Blueprint: Database Performance & Caching Patterns",
          filename: "Sandbox_Week3_Databases.pdf",
          totalPages: 32,
          downloadUrl: "/downloads/sample-guide.pdf",
          summary: "In-depth guide to indexing, query planning, and Redis memory management.",
          topicsCovered: ["Index Selectivity", "ACID Guarantees", "Cache Invalidation"],
          keyTakeaways: ["Prevent table scans", "Design zero-downtime database migrations"],
        },
      },
      {
        weekNumber: 4,
        title: "CI/CD Pipelines, Docker Containers & Production Capstone",
        theme: "Containerization, Cloud Deployment & Capstone Delivery",
        hours: 40,
        description: "Package the application into lightweight multi-stage Docker containers, configure CI/CD, and deploy live.",
        coreTopics: ["Docker Multi-Stage Builds", "GitHub Actions CI", "Secrets Management", "Production Logging"],
        practicalLabs: ["Build <50MB minimal Docker images", "Deploy automated release pipelines"],
        weeklyProject: {
          name: "Full-Stack Cloud Production Showcase Capstone",
          deliverable: "Live deployment URL and verified open-source repository",
          techStack: ["Next.js / Node.js", "Docker", "GitHub Actions"],
        },
        studyMaterial: {
          title: "Week 4 Blueprint: Containerization & Cloud Deployment",
          filename: "Sandbox_Week4_Deployment.pdf",
          totalPages: 26,
          downloadUrl: "/downloads/sample-guide.pdf",
          summary: "Essential blueprint for deploying robust, containerized applications to cloud platforms.",
          topicsCovered: ["Container Security", "Continuous Integration", "Observability"],
          keyTakeaways: ["Deploy production-ready code with confidence", "Complete capstone project"],
        },
      },
    ],
    codingChallenges: [
      {
        id: "sandbox-c1",
        title: "Interactive String Reversal & Anagram Verifier",
        difficulty: "BEGINNER",
        week: 1,
        points: 100,
        description:
          "Write a function that determines whether two input strings are valid anagrams of each other (ignoring whitespace and case) with O(1) auxiliary space.",
        inputFormat: "Two strings separated by '|', e.g. 'Listen | Silent'",
        outputFormat: "'true' or 'false'",
        constraints: ["Length of strings <= 10^5", "ASCII characters only"],
        sampleInput: "Listen | Silent",
        sampleOutput: "true",
        explanation: "Characters in 'Listen' can be rearranged to form 'Silent'.",
        starterCode: {
          python: `def solution(input_str: str) -> str:
    s1, s2 = [x.strip().lower() for x in input_str.split("|")]
    return "true" if sorted(s1) == sorted(s2) else "false"`,
          javascript: `function solution(inputStr) {
    const [s1, s2] = inputStr.split("|").map(s => s.trim().toLowerCase());
    return s1.split("").sort().join("") === s2.split("").sort().join("") ? "true" : "false";
}`,
          java: `import java.util.Arrays;

public class Solution {
    public static String solution(String inputStr) {
        String[] parts = inputStr.split("\\\\|");
        char[] a = parts[0].trim().toLowerCase().toCharArray();
        char[] b = parts[1].trim().toLowerCase().toCharArray();
        Arrays.sort(a);
        Arrays.sort(b);
        return Arrays.equals(a, b) ? "true" : "false";
    }
}`,
        },
        testCases: [
          { input: "listen | silent", expectedOutput: "true" },
          { input: "triangle | integral", expectedOutput: "true" },
          { input: "apple | pale", expectedOutput: "false" },
        ],
        hints: ["Sort both character arrays or count frequency buckets."],
      },
    ],
    capstoneProject: {
      title: "Interactive Full-Stack Architecture & Cloud Testing Sandbox",
      industryContext:
        "Build and test an end-to-end cloud-native microservice with automated unit tests, structured logs, and CI/CD validation.",
      architectureOverview:
        "Client Request -> Reverse Proxy -> Application Service -> Redis Cache -> Relational Database -> Logging Pipeline.",
      deliverables: [
        "Tested repository with full test suite passing in CI",
        "Documented architecture diagram and API endpoints in README",
        "Containerized Dockerfile ready for production deployment",
      ],
      gradingCriteria: [
        { item: "Code Modularity & Test Coverage", weight: 40 },
        { item: "Git Commit Quality & Branching", weight: 30 },
        { item: "Documentation & Readability", weight: 30 },
      ],
    },
  },

  // 1. Web Engineering
  {
    id: "web",
    slug: "web",
    title: "Modern Web Engineering & Core Browser Architecture",
    domain: "Web & Browser Systems",
    category: "WEB",
    icon: "🌐",
    badge: "Core Foundations",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master DOM rendering pipelines, critical rendering paths, V8 event loops, and web standards.",
    overview: "A deep dive into browser layout engines, CSSOM generation, web performance budgets, Service Workers, and responsive accessibility.",
    targetAudience: ["Frontend Engineers", "Full-Stack Developers", "UI/UX Systems Architects"],
    prerequisites: ["HTML5, CSS3, Modern JavaScript"],
    discordChannel: "#web-engineering",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-WEB",
      title: "Certified Modern Web & Browser Systems Engineer",
      designation: "Web Systems Engineer",
      skills: ["DOM Architecture", "Critical Rendering Path", "CSS Grid/Flexbox", "Service Workers", "Web Performance"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "High-Performance Browser-Native Media Player with Offline Storage",
      industryContext: "Build a zero-dependency web audio/video suite supporting local caching, offline sync, and 60fps animations.",
      architectureOverview: "Web Worker -> IndexedDB -> Canvas Render -> Web Audio API.",
      deliverables: ["PWA with offline capabilities", "Lighthouse 100/100 audit report"],
      gradingCriteria: [{ item: "Performance & FPS", weight: 50 }, { item: "Offline Sync", weight: 50 }],
    },
  },

  // 2. Git Engineering
  {
    id: "git",
    slug: "git",
    title: "Git Internals, Plumbing Protocols & Monorepo Workflows",
    domain: "DevOps & Developer Tooling",
    category: "GIT",
    icon: "🐙",
    badge: "Version Control Mastery",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master Git plumbing, tree hashing, submodules, sparse checkouts, and trunk-based releases.",
    overview: "Learn how Git works under the hood: the DAG, packfiles, cherry-picks, rebase re-writing, hooks, and scalable monorepo tooling.",
    targetAudience: ["Software Engineers", "DevOps Specialists", "Open Source Maintainers"],
    prerequisites: ["Basic command-line comfort"],
    discordChannel: "#git-internals",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-GIT",
      title: "Certified Git Internals & Version Control Systems Specialist",
      designation: "Release Engineer",
      skills: ["Git Plumbing", "Interactive Rebase", "Reflog Recovery", "Monorepo Workflows", "CI Automation"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Minimal Git Implementation in TypeScript / Python",
      industryContext: "Implement `init`, `hash-object`, `cat-file`, `write-tree`, and `commit-tree` from raw byte streams.",
      architectureOverview: "SHA-1 Hash Engine -> Zlib Compression -> Filesystem Storage.",
      deliverables: ["Working CLI binary", "Compatibility tests passing against real git repositories"],
      gradingCriteria: [{ item: "Byte-for-byte correctness", weight: 60 }, { item: "Clean CLI design", weight: 40 }],
    },
  },

  // 3. Next.js Fullstack
  {
    id: "nextjs",
    slug: "nextjs",
    title: "Next.js 15 App Router & Edge Server Actions Mastery",
    domain: "Full-Stack Web Architecture",
    category: "NEXTJS",
    icon: "⚡",
    badge: "Production Next.js 15",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Production React 19 Server Components, streaming SSR, edge caching, and server actions.",
    overview: "Build industrial SaaS platforms utilizing Next.js 15, partial prerendering, parallel routes, intercepting routes, and PostgreSQL persistence.",
    targetAudience: ["Full-Stack Developers", "Frontend Engineers", "SaaS Founders"],
    prerequisites: ["React, TypeScript"],
    discordChannel: "#nextjs-elite",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-NEXTJS",
      title: "Certified Next.js 15 App Router Architecture Specialist",
      designation: "Next.js Systems Architect",
      skills: ["Server Actions", "Streaming SSR", "Partial Prerendering", "Turbopack", "Edge Middleware"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Enterprise Multi-Tenant SaaS with Stripe Billing",
      industryContext: "Develop a multi-tenant workspace with custom subdomain routing, optimistic updates, and role-based permissions.",
      architectureOverview: "Edge Middleware -> App Router -> Server Actions -> Drizzle ORM.",
      deliverables: ["Live production URL", "Stripe webhook integration"],
      gradingCriteria: [{ item: "Architecture & Security", weight: 50 }, { item: "Performance", weight: 50 }],
    },
  },

  // 4. Database Management
  {
    id: "database-management",
    slug: "database-management",
    title: "Database Management & Storage Engine Engineering",
    domain: "Databases & Systems",
    category: "DATABASE",
    icon: "🗄️",
    badge: "Storage Engine Internals",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master B+ Trees, Write-Ahead Logs (WAL), ACID concurrency, buffer pool managers, and sharding.",
    overview: "Explore how databases persist and retrieve data safely: storage page layout, two-phase locking, MVCC, and replication topologies.",
    targetAudience: ["Backend Engineers", "Database Administrators", "Infrastructure Architects"],
    prerequisites: ["Data structures, basic SQL"],
    discordChannel: "#database-internals",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-DBM",
      title: "Certified Database Management & Storage Internals Specialist",
      designation: "Database Systems Engineer",
      skills: ["B+ Tree Indexes", "WAL & Recovery", "MVCC Concurrency", "Buffer Management", "Partitioning"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Embedded Key-Value Storage Engine with WAL",
      industryContext: "Build a disk-backed key-value store supporting atomic transactions, compaction, and crash recovery.",
      architectureOverview: "MemTable (SkipList) -> WAL -> SSTables -> Compaction Worker.",
      deliverables: ["Engine source code with crash recovery test suite", "Benchmarking script"],
      gradingCriteria: [{ item: "ACID Crash Durability", weight: 60 }, { item: "Throughput (OPS)", weight: 40 }],
    },
  },

  // 5. Networking
  {
    id: "networking",
    slug: "networking",
    title: "Computer Networking, Protocols & Cloud Infrastructure",
    domain: "Infrastructure & Networks",
    category: "NETWORKING",
    icon: "🔌",
    badge: "Protocol Mastery",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master TCP/IP, UDP, DNS resolution, TLS 1.3 handshakes, HTTP/3 QUIC, and packet inspection.",
    overview: "Learn socket programming, congestion control algorithms, NAT traversal, firewall configurations, and software-defined networking.",
    targetAudience: ["Systems Engineers", "DevOps Engineers", "Cybersecurity Researchers"],
    prerequisites: ["Operating systems basics, C/Python/Go basics"],
    discordChannel: "#networking-protocols",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-NET",
      title: "Certified Computer Networking & Protocol Systems Engineer",
      designation: "Network Systems Engineer",
      skills: ["TCP/IP Sockets", "TLS 1.3", "HTTP/3 QUIC", "Wireshark Packet Analysis", "DNS Routing"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "High-Concurrency Layer 4 TCP Reverse Proxy",
      industryContext: "Build a load-balancing reverse proxy supporting health checks, round-robin/least-connections, and connection pooling.",
      architectureOverview: "Epoll/Kqueue Socket Loop -> Buffer Ring -> Target Balancer.",
      deliverables: ["Functional binary capable of routing 50k req/s", "Wireshark PCAP verification report"],
      gradingCriteria: [{ item: "Throughput & Zero Dropped Packets", weight: 60 }, { item: "Connection Reuse", weight: 40 }],
    },
  },

  // 6. Web & Mobile Development
  {
    id: "web-mobile-dev",
    slug: "web-mobile-dev",
    title: "Cross-Platform Web & Mobile Development (React Native & Flutter)",
    domain: "Mobile & Universal Systems",
    category: "MOBILE",
    icon: "📱",
    badge: "Cross-Platform Universal",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build native iOS, Android, and Web apps with unified architecture, offline sync, and gesture animations.",
    overview: "Master cross-platform mobile architectures using React Native, Expo, Flutter, native bridge modules, SQLite offline caching, and push notifications.",
    targetAudience: ["Mobile Engineers", "Full-Stack App Builders", "Frontend Developers"],
    prerequisites: ["JavaScript/TypeScript or Dart"],
    discordChannel: "#mobile-dev",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-MOB",
      title: "Certified Cross-Platform Web & Mobile Development Specialist",
      designation: "Mobile Systems Engineer",
      skills: ["React Native", "Expo Router", "SQLite Offline First", "Biometric Auth", "Gesture Handler"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Offline-First Mobile Collaborative Workspace with Local Sync",
      industryContext: "Create a universal mobile/web notes and task app with biometric security and background cloud sync.",
      architectureOverview: "WatermelonDB/CRDT -> Mobile Native Bridge -> WebSocket Sync Server.",
      deliverables: ["Published APK/Expo preview link", "Open source repository"],
      gradingCriteria: [{ item: "Offline Conflict Resolution", weight: 50 }, { item: "Native Performance & UI", weight: 50 }],
    },
  },

  // 7. Data Scientist
  {
    id: "data-scientist",
    slug: "data-scientist",
    title: "Data Science, Statistical Modeling & Predictive Analytics",
    domain: "AI & Machine Learning",
    category: "DATA_SCIENCE",
    icon: "📊",
    badge: "Analytics & ML",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Transform messy real-world datasets into predictive statistical models and interactive business dashboards.",
    overview: "Master exploratory data analysis, hypothesis testing, feature engineering, Scikit-Learn, Polars, XGBoost, and model deployment pipelines.",
    targetAudience: ["Aspiring Data Scientists", "ML Analysts", "Quant Developers"],
    prerequisites: ["Python, Basic Statistics"],
    discordChannel: "#data-science",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-DS",
      title: "Certified Data Science & Predictive Analytics Practitioner",
      designation: "Data Scientist",
      skills: ["Feature Engineering", "Statistical Hypothesis Testing", "Polars / Pandas", "XGBoost", "Streamlit"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Automated Customer Churn & Fraud Prediction Engine",
      industryContext: "Train and deploy a production ML pipeline with automated drift detection and interactive dashboard.",
      architectureOverview: "Data Ingestion -> Feature Pipeline -> Model Training -> FastAPI Inference -> Streamlit UI.",
      deliverables: ["Jupyter research notebook", "Dockerized API with metrics"],
      gradingCriteria: [{ item: "Statistical Rigor & ROC-AUC", weight: 60 }, { item: "Deployment Setup", weight: 40 }],
    },
  },

  // 8. Game Development
  {
    id: "game-development",
    slug: "game-development",
    title: "Game Development, Physics Simulation & 3D Engines",
    domain: "Game Development & Graphics",
    category: "GAME_DEV",
    icon: "🎮",
    badge: "Interactive Graphics",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build high-performance 2D/3D games with collision detection, state machines, and real-time physics.",
    overview: "Explore game loop architecture, delta time simulation, spatial partitioning (quadtrees/octrees), audio engines, and particle effects.",
    targetAudience: ["Game Programmers", "C++/C# Developers", "Indie Game Creators"],
    prerequisites: ["Object-oriented programming, basic vector algebra"],
    discordChannel: "#game-development",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-GAME",
      title: "Certified Game Systems & Physics Simulation Engineer",
      designation: "Game Systems Programmer",
      skills: ["Game Loops", "Spatial Partitioning", "Collision Detection (AABB/SAT)", "Shader Basics", "Audio Integration"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "2.5D Arena Combat Simulator with Physics Engine",
      industryContext: "Program a real-time combat game with custom physics, enemy behavior trees, and particle systems.",
      architectureOverview: "Input Buffer -> Game State -> Physics Solver -> Render Pipeline -> Sound FX.",
      deliverables: ["Playable game build (WebAssembly or Desktop)", "Architecture documentation"],
      gradingCriteria: [{ item: "Physics & Framerate Stability (60fps)", weight: 60 }, { item: "Gameplay Feel & Polish", weight: 40 }],
    },
  },

  // 9. Web Game Dev
  {
    id: "web-game-dev",
    slug: "web-game-dev",
    title: "Web Game Development (Three.js, WebGL & Multiplayer WebSockets)",
    domain: "Game Development & Graphics",
    category: "WEB_GAME_DEV",
    icon: "🕹️",
    badge: "Browser 3D Gaming",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Develop browser-based 3D games with Three.js, WebGL shaders, and real-time multiplayer WebSockets.",
    overview: "Build lightweight browser games running at silky 60fps across phones and desktops: 3D scene graphs, lighting, client prediction, and multiplayer reconciliation.",
    targetAudience: ["Creative Coders", "Frontend Developers", "Interactive Web Creators"],
    prerequisites: ["JavaScript, basic 3D concepts"],
    discordChannel: "#web-game-dev",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-WGD",
      title: "Certified WebGL & Multiplayer Web Game Specialist",
      designation: "Web Game Developer",
      skills: ["Three.js", "WebGL Shaders", "Client Prediction", "WebSockets Sync", "Asset Optimization"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Real-Time Multiplayer 3D Space Arena in Browser",
      industryContext: "Develop a browser multiplayer dogfight game with authoritative server loop and latency compensation.",
      architectureOverview: "Node.js WebSocket Server -> Three.js Canvas Renderer -> Howler.js Audio.",
      deliverables: ["Live web playable link", "Source code with server tick rate benchmarks"],
      gradingCriteria: [{ item: "Multiplayer Synchronization", weight: 60 }, { item: "Visual Fidelity & 60fps", weight: 40 }],
    },
  },

  // 10. Blockchain
  {
    id: "blockchain",
    slug: "blockchain",
    title: "Blockchain Engineering, EVM Protocols & Smart Contract Security",
    domain: "Emerging Tech & Web3",
    category: "BLOCKCHAIN",
    icon: "⛓️",
    badge: "Decentralized Systems",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build decentralized protocols, audit Solidity smart contracts, and understand cryptographic consensus.",
    overview: "Study Ethereum virtual machine internals, gas optimization, re-entrancy attack prevention, Hardhat/Foundry testing, and zero-knowledge primitives.",
    targetAudience: ["Web3 Developers", "Security Auditors", "Protocol Engineers"],
    prerequisites: ["Solidity or TypeScript/Python"],
    discordChannel: "#blockchain-dev",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-BC",
      title: "Certified Blockchain Protocol & Smart Contract Security Engineer",
      designation: "Blockchain Protocol Engineer",
      skills: ["EVM Internals", "Foundry Test Suites", "Gas Optimization", "Re-entrancy Defense", "ERC-20/721 Standards"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Automated Decentralized Lending Vault with Slashing Logic",
      industryContext: "Implement an audited decentralized collateral vault with liquidations and mathematical formal verification.",
      architectureOverview: "Smart Contracts -> Foundry Tests -> TheGraph Indexer -> Ethers.js Frontend.",
      deliverables: ["Verified contract on Sepolia testnet", "Slither security audit report"],
      gradingCriteria: [{ item: "Contract Security & Gas Efficiency", weight: 70 }, { item: "Comprehensive Test Coverage", weight: 30 }],
    },
  },

  // 11. System Design
  {
    id: "system-design",
    slug: "system-design",
    title: "Large-Scale Distributed System Design & Architecture",
    domain: "Databases & Systems",
    category: "SYSTEM_DESIGN",
    icon: "📐",
    badge: "High-Scale Architecture",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Design systems that scale to 100M+ DAUs: rate limiters, message brokers, caching, and database partitioning.",
    overview: "Master modern microservice decomposition, event-driven architectures with Kafka, CAP theorem trade-offs, consistent hashing, and fault-tolerant failovers.",
    targetAudience: ["Senior Engineers", "Technical Leads", "System Architects"],
    prerequisites: ["Backend development experience"],
    discordChannel: "#system-design",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-SD",
      title: "Certified Large-Scale Distributed System Design Architect",
      designation: "Systems Architect",
      skills: ["Consistent Hashing", "Kafka Streaming", "Database Sharding", "Rate Limiting Algorithms", "Disaster Recovery"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Global Distributed URL Shortener & Analytics Ingestion Engine",
      industryContext: "Design and implement a system handling 100k requests/sec with Bloom filters, Redis caching, and ClickHouse aggregation.",
      architectureOverview: "Anycast DNS -> Envoy Proxy -> Token Bucket Limiter -> Key-Value Cache -> Columnar DB.",
      deliverables: ["Full architectural design manifesto", "Locust load-test benchmark report"],
      gradingCriteria: [{ item: "Architecture Completeness", weight: 50 }, { item: "Load Benchmark Performance", weight: 50 }],
    },
  },

  // 12. SaaS Engineering
  {
    id: "saas",
    slug: "saas",
    title: "Production SaaS Architecture, Multi-Tenancy & Billing Systems",
    domain: "Product & SaaS Engineering",
    category: "SAAS",
    icon: "💼",
    badge: "Commercial Software",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Architect commercial SaaS applications with multi-tenant data isolation, usage meters, and webhooks.",
    overview: "Learn enterprise SaaS patterns: database-per-tenant vs shared schema with row-level security (RLS), Stripe/Cashfree billing life-cycles, RBAC permissions, and audit logs.",
    targetAudience: ["Full-Stack Developers", "SaaS Founders", "Backend Engineers"],
    prerequisites: ["Web development, SQL database basics"],
    discordChannel: "#saas-architecture",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-SAAS",
      title: "Certified Production SaaS & Multi-Tenancy Systems Architect",
      designation: "SaaS Systems Engineer",
      skills: ["Row Level Security (RLS)", "Subscription Billing Lifecycles", "Webhook Idempotency", "RBAC Auth", "Audit Logging"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Commercial Multi-Tenant Team Collaboration Platform",
      industryContext: "Develop a complete B2B SaaS with team invitations, usage-based billing tiers, and cryptographically verified webhooks.",
      architectureOverview: "Next.js App Router -> Postgres RLS -> Redis Queue -> Stripe Billing Webhooks.",
      deliverables: ["Live production app with onboarding flow", "Webhook testing documentation"],
      gradingCriteria: [{ item: "Tenant Data Isolation Security", weight: 60 }, { item: "Billing & Subscription Flow", weight: 40 }],
    },
  },

  // 13. HealthTech
  {
    id: "health-tech",
    slug: "health-tech",
    title: "HealthTech Systems Engineering, HL7/FHIR Protocols & HIPAA Compliance",
    domain: "Industry & HealthTech",
    category: "HEALTH_TECH",
    icon: "🩺",
    badge: "Medical Software",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build secure, compliant healthcare software utilizing HL7/FHIR standard protocols and encrypted audit trails.",
    overview: "Explore the intersection of medicine and software engineering: Electronic Health Record (EHR) schemas, DICOM image viewer integration, and zero-knowledge medical data compliance.",
    targetAudience: ["Bioinformatics Engineers", "Healthcare Software Developers", "Security Officers"],
    prerequisites: ["Backend development, REST APIs"],
    discordChannel: "#health-tech",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-HT",
      title: "Certified HealthTech Architecture & FHIR Protocol Engineer",
      designation: "Healthcare Systems Engineer",
      skills: ["HL7/FHIR Protocols", "HIPAA/ABDM Standards", "Field-Level Encryption", "EHR Interoperability", "DICOM Imaging"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "FHIR-Compliant Telemedicine & Electronic Health Record Exchange",
      industryContext: "Build a standards-compliant patient portal that ingests and transforms HL7 messages into FHIR JSON resources securely.",
      architectureOverview: "FHIR REST Server -> Encrypted PostgreSQL -> DICOM Web Viewer -> Audit Logger.",
      deliverables: ["Compliant server implementation passing official FHIR test suites", "HIPAA security checklist"],
      gradingCriteria: [{ item: "FHIR Protocol Conformance", weight: 60 }, { item: "Security & Encryption Rigor", weight: 40 }],
    },
  },

  // 14. Compilers & Tooling
  {
    id: "compiler-tooling",
    slug: "compiler-tooling",
    title: "Compiler Construction, Bytecode VMs & Tooling Engineering",
    domain: "Systems & Compilers",
    category: "COMPILERS",
    icon: "⚙️",
    badge: "Low-Level Systems",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build a programming language from scratch: lexer, recursive descent parser, AST, and stack bytecode VM.",
    overview: "Dive into low-level systems programming: tokenization, BNF grammars, Abstract Syntax Trees, constant folding, and mark-sweep garbage collection.",
    targetAudience: ["Systems Programmers", "Language Enthusiasts", "Compiler Engineers"],
    prerequisites: ["C/C++, Rust, or Python/TypeScript basics"],
    discordChannel: "#compilers-systems",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-COMP",
      title: "Certified Compiler Construction & Bytecode Virtual Machine Engineer",
      designation: "Compiler Systems Engineer",
      skills: ["Lexical Tokenization", "Recursive Descent Parsing", "AST Representation", "Bytecode Virtual Machines", "Garbage Collection"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Complete Scripting Language with Bytecode VM & REPL",
      industryContext: "Implement a dynamically typed language with closures, arithmetic expressions, control flow, and a fast stack VM.",
      architectureOverview: "Source Text -> Scanner -> Parser -> Compiler -> Stack-Based VM -> Output.",
      deliverables: ["Working REPL executable with test suites", "Language specification document"],
      gradingCriteria: [{ item: "Parser & VM Correctness", weight: 60 }, { item: "Execution Speed & Memory Footprint", weight: 40 }],
    },
  },

  // 15. Automation & QA
  {
    id: "automation",
    slug: "automation",
    title: "Modern End-to-End QA Automation, Playwright & CI Pipelines",
    domain: "DevOps & Developer Tooling",
    category: "AUTOMATION",
    icon: "🤖",
    badge: "Automated Testing",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master enterprise web automation, parallel Playwright test suites, and self-healing CI/CD pipelines.",
    overview: "Build industrial test automation architectures: Page Object Models, API mocking, visual regression testing, network interception, and Dockerized test runners.",
    targetAudience: ["QA Automation Engineers", "SDETs", "Full-Stack Engineers"],
    prerequisites: ["JavaScript/TypeScript or Python basics"],
    discordChannel: "#qa-automation",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-AUTO",
      title: "Certified Software Development Engineer in Test (SDET)",
      designation: "SDET Automation Engineer",
      skills: ["Playwright E2E", "Page Object Model", "Visual Regression", "API Contract Testing", "GitHub Actions CI"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Enterprise Multi-Browser Regression Suite with Real-Time Video Reporting",
      industryContext: "Architect an automated test framework testing a complete banking/e-commerce workflow across Chromium, Firefox, and WebKit.",
      architectureOverview: "Playwright Test Runner -> Parallel Worker Grid -> Allure Reporting -> Slack Alerting.",
      deliverables: ["Automated GitHub Actions CI pipeline with reports", "Zero flaky tests proof"],
      gradingCriteria: [{ item: "Test Robustness & Selectors", weight: 60 }, { item: "CI/CD Execution Speed", weight: 40 }],
    },
  },

  // 16. Advanced SQL
  {
    id: "sql",
    slug: "sql",
    title: "Advanced SQL Engineering, PostgreSQL Internals & Query Tuning",
    domain: "Databases & Systems",
    category: "SQL",
    icon: "🐬",
    badge: "Query Optimization",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master window functions, recursive CTEs, query planning, partial indexes, and deadlock analysis.",
    overview: "Transform slow multi-second database queries into sub-millisecond execution plans using PostgreSQL query profiling, lateral joins, and partition pruning.",
    targetAudience: ["Backend Developers", "Data Engineers", "Database Specialists"],
    prerequisites: ["Basic SQL queries"],
    discordChannel: "#advanced-sql",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-SQL",
      title: "Certified Advanced SQL & PostgreSQL Performance Specialist",
      designation: "Database Optimization Engineer",
      skills: ["Window Functions", "Recursive CTEs", "EXPLAIN ANALYZE", "GIN/BRIN Indexes", "Partition Pruning"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "10-Million Row Analytical Query Optimization Benchmark",
      industryContext: "Refactor and optimize complex financial reporting queries over 10M rows to execute under 50ms consistently.",
      architectureOverview: "PostgreSQL Database -> EXPLAIN Plan Tuner -> Materialized Views -> Partial Indexes.",
      deliverables: ["Performance benchmark audit comparing before and after latency", "Optimized schema migration"],
      gradingCriteria: [{ item: "Latency Reduction Percentage", weight: 70 }, { item: "Query Elegance & Maintainability", weight: 30 }],
    },
  },

  // 17. SRE
  {
    id: "sre",
    slug: "sre",
    title: "Site Reliability Engineering (SRE), Chaos & Observability",
    domain: "Infrastructure & Networks",
    category: "SRE",
    icon: "🛡️",
    badge: "High Reliability",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Design 99.99% uptime systems: SLIs, SLOs, error budgets, Prometheus metrics, and chaos experiments.",
    overview: "Learn modern reliability engineering practices: distributed tracing with OpenTelemetry, incident post-mortems, Grafana dashboards, and automated failovers.",
    targetAudience: ["SREs", "Cloud Engineers", "Production Support Architects"],
    prerequisites: ["Linux, basic cloud concepts"],
    discordChannel: "#sre-observability",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-SRE",
      title: "Certified Site Reliability & Chaos Engineering Specialist",
      designation: "Site Reliability Engineer",
      skills: ["SLIs/SLOs/Error Budgets", "Prometheus & Grafana", "OpenTelemetry Tracing", "Chaos Mesh", "Incident Runbooks"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Production Observability Pipeline with Automated Chaos Injections",
      industryContext: "Deploy a microservice cluster, inject simulated network partitions and CPU spikes, and verify automated recovery.",
      architectureOverview: "Kubernetes/Docker -> OpenTelemetry Collector -> Prometheus -> Grafana Dashboard.",
      deliverables: ["Complete Grafana dashboard JSON", "Post-mortem incident analysis report"],
      gradingCriteria: [{ item: "Observability Telemetry Coverage", weight: 50 }, { item: "Chaos Recovery Automation", weight: 50 }],
    },
  },

  // 18. SEO & Web Performance
  {
    id: "seo",
    slug: "seo",
    title: "Technical SEO, Core Web Vitals & Web Performance Optimization",
    domain: "Growth & Web Performance",
    category: "SEO",
    icon: "📈",
    badge: "Web Performance & SEO",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Optimize web platforms for Google indexing, Core Web Vitals (LCP, INP, CLS), and viral crawl efficiency.",
    overview: "Master deep technical SEO: semantic JSON-LD structured data, dynamic XML sitemaps, robots protocol, edge caching, and minimizing Cumulative Layout Shift.",
    targetAudience: ["Web Developers", "SEO Engineers", "Technical Marketers"],
    prerequisites: ["HTML, Web development basics"],
    discordChannel: "#seo-performance",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-SEO",
      title: "Certified Technical SEO & Core Web Vitals Optimization Specialist",
      designation: "Technical SEO Engineer",
      skills: ["Core Web Vitals (LCP/INP/CLS)", "JSON-LD Schema", "Dynamic Sitemaps", "SSR Prerendering", "Crawl Budget Optimization"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "100,000-Page High-Velocity Indexable Knowledge Platform",
      industryContext: "Build a programmatically generated knowledge base achieving sub-800ms LCP and 100% Google Rich Results validity.",
      architectureOverview: "Next.js Static Generation -> JSON-LD Schema Injector -> Edge CDN -> Sitemap Streamer.",
      deliverables: ["Google Search Console inspection validation", "Lighthouse 100/100 Core Web Vitals report"],
      gradingCriteria: [{ item: "Core Web Vitals Metric Scores", weight: 60 }, { item: "Structured Data Validity", weight: 40 }],
    },
  },

  // 19. Computer Vision
  {
    id: "computer-vision",
    slug: "computer-vision",
    title: "Computer Vision, Deep Learning, OpenCV & YOLO Object Detection",
    domain: "AI & Machine Learning",
    category: "COMPUTER_VISION",
    icon: "👁️",
    badge: "Visual AI",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build real-time image recognition, object detection, and visual segmentation pipelines with PyTorch and OpenCV.",
    overview: "Explore convolutional neural networks (CNNs), transfer learning, bounding box regression with YOLOv8, image filters, and edge inference.",
    targetAudience: ["AI Engineers", "Robotics Developers", "Python Programmers"],
    prerequisites: ["Python, Basic linear algebra"],
    discordChannel: "#computer-vision",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-CV",
      title: "Certified Computer Vision & Real-Time Object Detection Specialist",
      designation: "Computer Vision Engineer",
      skills: ["OpenCV Kernels", "CNN Architectures", "YOLOv8 Inference", "Data Augmentation", "Edge Quantization"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Real-Time Multi-Object Tracking & Counting System in Video",
      industryContext: "Implement a video processing pipeline that detects and tracks multiple moving targets in real time with Kalman filters.",
      architectureOverview: "OpenCV Video Stream -> YOLOv8 Tensor -> DeepSORT Tracking -> Metrics Overlay.",
      deliverables: ["Demonstration video analysis", "Inference benchmark documentation on CPU & GPU"],
      gradingCriteria: [{ item: "Tracking Accuracy (mAP)", weight: 60 }, { item: "FPS Processing Latency", weight: 40 }],
    },
  },

  // 20. Graphics Engineering
  {
    id: "graphics-engineering",
    slug: "graphics-engineering",
    title: "Graphics Engineering, Shaders (GLSL), Vulkan & OpenGL",
    domain: "Game Development & Graphics",
    category: "GRAPHICS",
    icon: "🎨",
    badge: "Low-Level Graphics",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master GPU programming: vertex & fragment shaders, rasterization, framebuffers, and ray tracing mathematics.",
    overview: "Write custom GPU shaders in GLSL, implement Blinn-Phong lighting models, shadow mapping, post-processing filters, and Vulkan command buffers.",
    targetAudience: ["Graphics Programmers", "Shader Artists", "GPU Engineers"],
    prerequisites: ["C/C++ or WebGL, 3D math (matrices, vectors)"],
    discordChannel: "#graphics-engineering",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-GFX",
      title: "Certified Graphics Engineering & GPU Shader Specialist",
      designation: "Graphics Systems Programmer",
      skills: ["GLSL Shaders", "Render Pipelines", "Shadow Mapping", "Post-Processing Effects", "GPU Memory Management"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Real-Time Deferred Rendering Engine with Volumetric Lighting",
      industryContext: "Build a rendering engine featuring multiple point lights, G-buffer creation, and Screen-Space Ambient Occlusion (SSAO).",
      architectureOverview: "Geometry Pass -> G-Buffer -> Lighting Pass -> SSAO Filter -> Tonemapping.",
      deliverables: ["Compiled executable demonstrating custom shaders", "Technical rendering breakdown write-up"],
      gradingCriteria: [{ item: "Visual Realism & Lighting Math", weight: 60 }, { item: "GPU Performance & Frame Times", weight: 40 }],
    },
  },

  // 21. Developer Tooling
  {
    id: "developer-tooling",
    slug: "developer-tooling",
    title: "Developer Tooling, CLI Architecture & Language Server Protocols",
    domain: "Systems & Compilers",
    category: "DEV_TOOLING",
    icon: "🛠️",
    badge: "DevEx Engineering",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build high-speed CLIs, code linters, Language Server Protocols (LSP), and monorepo bundlers.",
    overview: "Craft tools that other developers love: terminal UI frameworks, AST code transformations, custom ESLint plugins, and language server diagnostics.",
    targetAudience: ["Developer Experience Engineers", "Platform Engineers", "Infrastructure Toolmakers"],
    prerequisites: ["TypeScript or Go/Rust"],
    discordChannel: "#developer-tooling",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-DEV",
      title: "Certified Developer Tooling & Platform Experience Engineer",
      designation: "DevEx Systems Engineer",
      skills: ["Language Server Protocol (LSP)", "AST Code Analysis", "CLI Terminal UX", "Bundler Internals", "Custom Linters"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "High-Speed Code Linter & LSP Server for Custom DSL",
      industryContext: "Create a functional Language Server Protocol daemon supporting autocompletion, error diagnostics, and formatting in VS Code.",
      architectureOverview: "JSON-RPC Protocol -> AST Parser -> Diagnostics Engine -> Editor Extension.",
      deliverables: ["Published VS Code extension or standalone CLI", "Integration test suite"],
      gradingCriteria: [{ item: "LSP Protocol Compliance", weight: 60 }, { item: "Diagnostic Latency (<10ms)", weight: 40 }],
    },
  },

  // 22. TypeScript & JavaScript Internals
  {
    id: "ts-js",
    slug: "ts-js",
    title: "Modern TypeScript Generics & Deep JavaScript V8 Internals",
    domain: "Programming Languages",
    category: "TS_JS",
    icon: "🟨",
    badge: "Language Internals",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Master advanced TypeScript conditional types, V8 hidden classes, JIT compilation, and memory leaks.",
    overview: "Deep dive into the JavaScript runtime: call stacks, microtask vs macrotask execution, prototype chains, memory profiling with Chrome DevTools, and complex TypeScript type-level programming.",
    targetAudience: ["JavaScript Developers", "TypeScript Architects", "Frontend Performance Engineers"],
    prerequisites: ["Intermediate JavaScript / TypeScript"],
    discordChannel: "#ts-js-internals",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-TSJS",
      title: "Certified Modern TypeScript & V8 Engine Architecture Specialist",
      designation: "TypeScript Systems Engineer",
      skills: ["Type-Level Programming", "V8 Hidden Classes & ICs", "Event Loop Microtasks", "Heap Snapshot Profiling", "WASM Integration"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Zero-Overhead Type-Safe ORM Schema Validator & Benchmark",
      industryContext: "Build a TypeScript type-safe schema validator with compile-time type inference and runtime zero-copy parsing.",
      architectureOverview: "Conditional Type Inference -> JIT Generated Validator Function -> Memory Buffer.",
      deliverables: ["NPM publishable library", "Benchmark comparing throughput vs Zod and TypeBox"],
      gradingCriteria: [{ item: "Type-Level Correctness", weight: 50 }, { item: "Parsing Throughput Performance", weight: 50 }],
    },
  },

  // 23. CDN Architecture
  {
    id: "cdn-architecture",
    slug: "cdn-architecture",
    title: "Edge CDN Architecture, Anycast DNS & Origin Shielding",
    domain: "Infrastructure & Networks",
    category: "CDN",
    icon: "🌍",
    badge: "Edge Delivery",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Architect globally distributed Content Delivery Networks with Anycast routing, edge TTLs, and instant purge.",
    overview: "Understand edge caching topologies: cache hit ratios (CHR), stale-while-revalidate headers, byte-range requests, origin shielding, and DDoS mitigation at layer 7.",
    targetAudience: ["DevOps Engineers", "Cloud Architects", "Infrastructure Specialists"],
    prerequisites: ["HTTP protocols, networking fundamentals"],
    discordChannel: "#cdn-architecture",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-CDN",
      title: "Certified Edge CDN & Content Delivery Systems Architect",
      designation: "CDN Infrastructure Engineer",
      skills: ["Anycast Routing", "Cache Invalidation Topologies", "Stale-While-Revalidate", "Origin Shielding", "Edge Rate Limiting"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Edge Caching Reverse Proxy with Instant Tag-Based Purging",
      industryContext: "Build a caching proxy that intercepts HTTP requests, caches static/SSR assets in Redis/Memory, and supports surrogate-key instant invalidation.",
      architectureOverview: "Client -> Edge Worker -> Shared Cache Store -> Origin Server.",
      deliverables: ["Working caching proxy server", "Stress test report verifying 99% cache hit latency"],
      gradingCriteria: [{ item: "Cache Invalidation Correctness", weight: 60 }, { item: "Sub-10ms Response Latency", weight: 40 }],
    },
  },

  // 24. Reverse Engineering
  {
    id: "reverse-engineering",
    slug: "reverse-engineering",
    title: "Binary Reverse Engineering, Assembly & Malware Analysis",
    domain: "Cybersecurity & Defense",
    category: "REVERSE_ENG",
    icon: "🔬",
    badge: "Binary Analysis",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Dissect compiled executables: x86/ARM assembly, Ghidra decompilation, debugging, and binary patching.",
    overview: "Master binary analysis techniques: executable formats (ELF, PE), stack frames, buffer overflow exploitation, anti-debugging evasion, and binary instrumentation.",
    targetAudience: ["Security Researchers", "Penetration Testers", "Systems Programmers"],
    prerequisites: ["Basic C programming, assembly concepts"],
    discordChannel: "#reverse-engineering",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-REV",
      title: "Certified Binary Reverse Engineering & Security Analysis Specialist",
      designation: "Reverse Engineering Specialist",
      skills: ["x86/x64 Assembly", "Ghidra Decompilation", "GDB Debugging", "Binary Patching", "Vulnerability Discovery"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Decompilation & Binary Patching of Protected License Verification",
      industryContext: "Analyze a compiled binary target, identify cryptographic validation bottlenecks, and patch the assembly to bypass software restrictions.",
      architectureOverview: "Binary Disassembly -> Call Graph Reconstruction -> Patch Generation -> Dynamic Verification.",
      deliverables: ["Comprehensive reverse engineering report", "Functional binary patch file (diff)"],
      gradingCriteria: [{ item: "Disassembly Accuracy", weight: 60 }, { item: "Report Thoroughness & Methodology", weight: 40 }],
    },
  },

  // 25. Edge Computing
  {
    id: "edge-computing",
    slug: "edge-computing",
    title: "Edge Computing, Serverless WASM & Globally Distributed State",
    domain: "Infrastructure & Networks",
    category: "EDGE",
    icon: "⚡",
    badge: "Edge Cloud",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Deploy sub-millisecond serverless compute at the edge: Cloudflare Workers, WASM modules, and edge KV stores.",
    overview: "Explore distributed edge computing models: execution environments with V8 isolates, WebAssembly runtimes, distributed consistency at the edge, and cold-start elimination.",
    targetAudience: ["Cloud Engineers", "Serverless Developers", "Systems Architects"],
    prerequisites: ["TypeScript or Rust, basic cloud knowledge"],
    discordChannel: "#edge-computing",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-EDGE",
      title: "Certified Edge Computing & Serverless WebAssembly Specialist",
      designation: "Edge Systems Engineer",
      skills: ["V8 Isolates", "WebAssembly (WASM)", "Edge KV Stores", "Zero Cold-Start Architecture", "Global Request Routing"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Globally Distributed Edge Rate Limiter with Geo-Replication",
      industryContext: "Deploy an edge middleware application that authenticates and rate-limits API requests at the edge before hitting the origin server.",
      architectureOverview: "Edge Worker -> Distributed KV -> WASM Token Bucket -> Target Origin.",
      deliverables: ["Deployed edge worker URL", "Global latency benchmark report from 10 world regions"],
      gradingCriteria: [{ item: "Sub-15ms Global Response Time", weight: 60 }, { item: "Distributed State Sync", weight: 40 }],
    },
  },

  // 26. Distributed Systems
  {
    id: "distributed-systems",
    slug: "distributed-systems",
    title: "Distributed Systems Engineering, Raft Consensus & Fault Tolerance",
    domain: "Databases & Systems",
    category: "DISTRIBUTED_SYS",
    icon: "🌐",
    badge: "Consensus & Protocols",
    durationWeeks: 4,
    totalHours: 160,
    pricing: { originalPrice: 1999, discountedPrice: 499, currency: "INR" },
    tagline: "Build fault-tolerant distributed algorithms: Raft leader elections, log replication, vector clocks, and gossip protocols.",
    overview: "Master distributed systems theory and practice: network partitions, split-brain prevention, linearizability, distributed locks, and Paxos/Raft consensus implementations.",
    targetAudience: ["Distributed Systems Engineers", "Backend Architects", "Infrastructure Specialists"],
    prerequisites: ["Concurrency, networking, Go/Python/Rust"],
    discordChannel: "#distributed-systems",
    discordInviteUrl: "https://discord.gg/rolenest",
    collegeRecognition: {
      academicCredits: "4 Credits Recommended (AICTE/UGC Credit Framework)",
      aicteCompliant: true,
      includesNocLetter: true,
      acceptanceGuarantee: "Official University Acceptance Guarantee",
    },
    certificateSpec: {
      prefix: "RN-INT-DIST",
      title: "Certified Distributed Systems & Consensus Protocol Engineer",
      designation: "Distributed Systems Architect",
      skills: ["Raft Consensus", "Leader Election", "Log Replication", "Vector Clocks", "Linearizable Consistency"],
    },
    weeks: [],
    codingChallenges: [],
    capstoneProject: {
      title: "Production-Grade Raft Distributed Consensus Key-Value Cluster",
      industryContext: "Implement a 3-node distributed cluster maintaining linearizable consensus during simulated node failure and network partitions.",
      architectureOverview: "Raft Node State Machine -> AppendEntries RPC -> State Machine Replication -> Jepsen Test Suite.",
      deliverables: ["Cluster implementation with passing partition test suite", "Linearizability proof log"],
      gradingCriteria: [{ item: "Partition Recovery Correctness", weight: 70 }, { item: "Log Replication Speed", weight: 30 }],
    },
  },
];
