export interface CanvasNodeResource {
  title: string;
  url: string;
  type: "video" | "doc" | "course" | "exercise";
  provider: string;
  isFree: boolean;
}

export interface CanvasNode {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  level: "Foundational" | "Intermediate" | "Advanced" | "Capstone";
  x: number;
  y: number;
  dependencies: string[];
  estimatedHours: number;
  matchedJobsCount: number;
  skills: string[];
  description: string;
  projectTask: string;
  resources: CanvasNodeResource[];
}

export interface CanvasTrack {
  id: string;
  title: string;
  badge: string;
  targetRoles: string[];
  description: string;
  nodes: CanvasNode[];
}

export const CANVAS_TRACKS: CanvasTrack[] = [
  {
    id: "fullstack-web",
    title: "Full-Stack Web Engineering",
    badge: "Most In-Demand (India & Global Remote)",
    targetRoles: ["Full Stack Developer", "Frontend Engineer", "Next.js Specialist"],
    description: "Master modern web development from semantic HTML & TypeScript through Next.js 15, PostgreSQL, and scalable Cloudflare edge infrastructure.",
    nodes: [
      {
        id: "web-foundations",
        title: "Web Foundations",
        subtitle: "HTML5 & CSS3 Standards",
        category: "Frontend",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 15,
        matchedJobsCount: 18,
        skills: ["HTML", "CSS", "Responsive Design"],
        description: "Master semantic markup, flexbox, CSS grid, accessible ARIA landmarks, and mobile-first responsive layouts.",
        projectTask: "Build an accessible, responsive developer portfolio with dark/light themes without JavaScript frameworks.",
        resources: [
          { title: "MDN Web Docs: HTML & CSS", url: "https://developer.mozilla.org", type: "doc", provider: "MDN", isFree: true },
          { title: "CS50 Web Programming: HTML & CSS", url: "https://cs50.harvard.edu/web", type: "course", provider: "Harvard CS50", isFree: true },
        ],
      },
      {
        id: "js-core",
        title: "Modern JavaScript",
        subtitle: "ES2024 & Asynchronous Flow",
        category: "Core Language",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["web-foundations"],
        estimatedHours: 25,
        matchedJobsCount: 26,
        skills: ["JavaScript", "Promises", "Event Loop", "DOM APIs"],
        description: "Deep dive into execution context, closures, event loop microtasks, async/await, and functional programming constructs.",
        projectTask: "Build a client-side search engine with debouncing, localStorage caching, and infinite scrolling.",
        resources: [
          { title: "JavaScript.info: Modern Tutorial", url: "https://javascript.info", type: "doc", provider: "Open Book", isFree: true },
          { title: "Namaste JavaScript", url: "https://youtube.com", type: "video", provider: "Akshay Saini", isFree: true },
        ],
      },
      {
        id: "ts-mastery",
        title: "TypeScript Strict",
        subtitle: "Type Safety & Interfaces",
        category: "Type System",
        level: "Intermediate",
        x: 660,
        y: 90,
        dependencies: ["js-core"],
        estimatedHours: 20,
        matchedJobsCount: 22,
        skills: ["TypeScript", "Generics", "Zod Validation"],
        description: "Enforce zero-any policies, master union types, generic constraints, conditional types, and runtime schema validation with Zod.",
        projectTask: "Build a strictly typed REST client with Zod request/response contracts and discriminated unions.",
        resources: [
          { title: "Total TypeScript Essentials", url: "https://totaltypescript.com", type: "course", provider: "Matt Pocock", isFree: true },
          { title: "TypeScript Official Handbook", url: "https://typescriptlang.org/docs", type: "doc", provider: "Microsoft", isFree: true },
        ],
      },
      {
        id: "react-ecosystem",
        title: "React 19 & Architecture",
        subtitle: "Component Lifecycle & State",
        category: "Frontend",
        level: "Intermediate",
        x: 660,
        y: 270,
        dependencies: ["js-core"],
        estimatedHours: 30,
        matchedJobsCount: 29,
        skills: ["React", "Custom Hooks", "Context API"],
        description: "Learn reconciliation, concurrent features, custom hooks, atomic component boundaries, and render memoization.",
        projectTask: "Build an interactive Kanban board with drag-and-drop state, optimistic UI updates, and undo/redo history.",
        resources: [
          { title: "React Official Interactive Docs", url: "https://react.dev", type: "doc", provider: "React Team", isFree: true },
          { title: "Full Stack Open: React Section", url: "https://fullstackopen.com/en", type: "course", provider: "Univ of Helsinki", isFree: true },
        ],
      },
      {
        id: "tailwind-styling",
        title: "Tailwind CSS & UI",
        subtitle: "Design Systems & Radix",
        category: "Design",
        level: "Intermediate",
        x: 960,
        y: 90,
        dependencies: ["ts-mastery", "react-ecosystem"],
        estimatedHours: 12,
        matchedJobsCount: 16,
        skills: ["Tailwind CSS", "shadcn/ui", "Radix Primitives"],
        description: "Create accessible design systems using utility-first CSS, component tokens, animation transitions, and headless primitives.",
        projectTask: "Design and implement a responsive analytics dashboard with animated charts and dark-mode tokens.",
        resources: [
          { title: "Tailwind CSS Documentation", url: "https://tailwindcss.com/docs", type: "doc", provider: "Tailwind Labs", isFree: true },
        ],
      },
      {
        id: "nextjs-fullstack",
        title: "Next.js 15 App Router",
        subtitle: "Server Components & Edge",
        category: "Full Stack",
        level: "Advanced",
        x: 960,
        y: 270,
        dependencies: ["react-ecosystem"],
        estimatedHours: 35,
        matchedJobsCount: 28,
        skills: ["Next.js", "Server Actions", "Turborepo"],
        description: "Master React Server Components (RSC), dynamic caching strategies, Server Actions, streaming SSR, and edge middleware.",
        projectTask: "Build an authenticated multi-tenant CMS with server actions, optimistic mutations, and SEO metadata.",
        resources: [
          { title: "Next.js Official Learn Course", url: "https://nextjs.org/learn", type: "course", provider: "Vercel", isFree: true },
        ],
      },
      {
        id: "database-backend",
        title: "PostgreSQL & Drizzle",
        subtitle: "Relational Modeling & ORM",
        category: "Backend",
        level: "Advanced",
        x: 1260,
        y: 180,
        dependencies: ["nextjs-fullstack", "tailwind-styling"],
        estimatedHours: 25,
        matchedJobsCount: 24,
        skills: ["PostgreSQL", "Drizzle ORM", "Redis", "Cloudflare R2"],
        description: "Design relational database schemas, indexes, foreign keys, migrations, transactions, and Redis distributed caching.",
        projectTask: "Implement a transactional booking system with row-level locking, automated migrations, and audit logging.",
        resources: [
          { title: "PostgreSQL Tutorial for Beginners", url: "https://postgresqltutorial.com", type: "doc", provider: "PostgreSQL Guide", isFree: true },
          { title: "Drizzle ORM Official Guide", url: "https://orm.drizzle.team", type: "doc", provider: "Drizzle Team", isFree: true },
        ],
      },
      {
        id: "web-capstone",
        title: "Full-Stack SaaS Capstone",
        subtitle: "Production Deployment",
        category: "Capstone",
        level: "Capstone",
        x: 1560,
        y: 180,
        dependencies: ["database-backend"],
        estimatedHours: 40,
        matchedJobsCount: 31,
        skills: ["Full Stack Architecture", "Auth.js", "Cloudflare Pages", "OCI Deployment"],
        description: "Build, test, and deploy a complete production web platform with authentication, database persistence, and background jobs.",
        projectTask: "Ship a complete SaaS product with GitHub OAuth, transactional email, stripe mock or real payments, and live custom domain.",
        resources: [
          { title: "SaaS Boilerplate Guide", url: "https://github.com", type: "exercise", provider: "JobMint Academy", isFree: true },
        ],
      },
    ],
  },
  {
    id: "ai-ml-llm",
    title: "AI/ML & LLM Systems",
    badge: "Highest Salary Potential (USD Remote)",
    targetRoles: ["AI Engineer", "Machine Learning Specialist", "LLM Application Developer"],
    description: "From Python & NumPy fundamentals to PyTorch neural networks, open-source Llama 3.2 model inference, Vector DBs, and autonomous RAG agents.",
    nodes: [
      {
        id: "python-foundations",
        title: "Python 3 & Algorithms",
        subtitle: "Core Computing Syntax",
        category: "Core Language",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 20,
        matchedJobsCount: 25,
        skills: ["Python", "OOP", "Data Structures"],
        description: "Master Pythonic idioms, list comprehensions, generators, decorators, file I/O, and OOP architecture.",
        projectTask: "Build an automated CLI data scraper that extracts job postings and outputs clean structured JSON.",
        resources: [
          { title: "Harvard CS50P: Python Programming", url: "https://cs50.harvard.edu/python", type: "course", provider: "Harvard University", isFree: true },
        ],
      },
      {
        id: "data-numpy-pandas",
        title: "NumPy & Pandas",
        subtitle: "Vectorized Computations",
        category: "Data Science",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["python-foundations"],
        estimatedHours: 20,
        matchedJobsCount: 21,
        skills: ["NumPy", "Pandas", "Matplotlib"],
        description: "Learn array slicing, vectorized matrix operations, DataFrame aggregation, cleaning dirty data, and statistical visualization.",
        projectTask: "Perform an exploratory data analysis (EDA) on a 100,000-row salary dataset with outlier detection and distribution plots.",
        resources: [
          { title: "Kaggle: Pandas & Python Micro-Courses", url: "https://kaggle.com/learn", type: "course", provider: "Kaggle", isFree: true },
        ],
      },
      {
        id: "ml-classical",
        title: "Classical Machine Learning",
        subtitle: "Scikit-Learn & Modeling",
        category: "Machine Learning",
        level: "Intermediate",
        x: 660,
        y: 90,
        dependencies: ["data-numpy-pandas"],
        estimatedHours: 25,
        matchedJobsCount: 19,
        skills: ["Scikit-Learn", "Regression", "Classification", "Cross-Validation"],
        description: "Implement linear regression, decision trees, random forests, clustering, feature engineering, and precision/recall metrics.",
        projectTask: "Train and tune a churn prediction model with cross-validation and ROC-AUC evaluation curve.",
        resources: [
          { title: "Andrew Ng: Machine Learning Specialization", url: "https://coursera.org", type: "course", provider: "Stanford / DeepLearning.AI", isFree: true },
        ],
      },
      {
        id: "deep-learning-pytorch",
        title: "PyTorch & Neural Nets",
        subtitle: "Tensors & Backpropagation",
        category: "Deep Learning",
        level: "Intermediate",
        x: 660,
        y: 270,
        dependencies: ["data-numpy-pandas"],
        estimatedHours: 35,
        matchedJobsCount: 22,
        skills: ["PyTorch", "Backpropagation", "CNNs", "Autograd"],
        description: "Build micrograd from scratch, understand backpropagation math, tensor operations, optimizers, and neural loss functions.",
        projectTask: "Implement and train a multi-layer perceptron from scratch on GPU using PyTorch tensors.",
        resources: [
          { title: "Andrej Karpathy: Neural Networks Zero to Hero", url: "https://karpathy.ai/zero-to-hero.html", type: "video", provider: "Andrej Karpathy", isFree: true },
          { title: "Fast.ai: Practical Deep Learning for Coders", url: "https://course.fast.ai", type: "course", provider: "Fast.ai", isFree: true },
        ],
      },
      {
        id: "transformers-nlp",
        title: "Transformers & HuggingFace",
        subtitle: "Self-Attention & LLM Foundations",
        category: "Generative AI",
        level: "Advanced",
        x: 960,
        y: 180,
        dependencies: ["ml-classical", "deep-learning-pytorch"],
        estimatedHours: 30,
        matchedJobsCount: 26,
        skills: ["HuggingFace", "Attention Mechanism", "Tokenization"],
        description: "Understand the 'Attention Is All You Need' paper, multi-head attention, positional embeddings, and HuggingFace pipelines.",
        projectTask: "Fine-tune a lightweight BERT or DistilBERT model for multi-class resume category classification.",
        resources: [
          { title: "Hugging Face NLP Course", url: "https://huggingface.co/learn/nlp-course", type: "course", provider: "Hugging Face", isFree: true },
        ],
      },
      {
        id: "rag-vectordb",
        title: "RAG & Vector Databases",
        subtitle: "Embeddings & Semantic Search",
        category: "Generative AI",
        level: "Advanced",
        x: 1260,
        y: 90,
        dependencies: ["transformers-nlp"],
        estimatedHours: 25,
        matchedJobsCount: 27,
        skills: ["Vector DBs", "Embeddings", "Pinecone", "ChromaDB", "pgvector"],
        description: "Chunking strategies, dense embeddings, vector indexing (HNSW, IVFFlat), hybrid search, and hallucination reduction.",
        projectTask: "Build a document Q&A system using pgvector and Llama 3.2 with source citation.",
        resources: [
          { title: "Pinecone Learning Center: Vector Search Explained", url: "https://pinecone.io/learn", type: "doc", provider: "Pinecone", isFree: true },
        ],
      },
      {
        id: "llm-agents",
        title: "LLM Agents & Tool Calling",
        subtitle: "Function Calling & Orchestration",
        category: "Generative AI",
        level: "Advanced",
        x: 1260,
        y: 270,
        dependencies: ["transformers-nlp"],
        estimatedHours: 30,
        matchedJobsCount: 28,
        skills: ["LangChain", "Llama 3.2", "Groq API", "Function Calling"],
        description: "ReAct prompting, autonomous tool-use, multi-agent coordination, memory persistence, and low-latency inference on Groq.",
        projectTask: "Build an autonomous GitHub PR review agent that pulls code, analyzes security flaws, and comments suggestions.",
        resources: [
          { title: "DeepLearning.AI: Functions, Tools & Agents", url: "https://deeplearning.ai", type: "course", provider: "DeepLearning.AI", isFree: true },
        ],
      },
      {
        id: "ai-capstone",
        title: "Autonomous AI Agent System",
        subtitle: "Production LLM Application",
        category: "Capstone",
        level: "Capstone",
        x: 1560,
        y: 180,
        dependencies: ["rag-vectordb", "llm-agents"],
        estimatedHours: 45,
        matchedJobsCount: 30,
        skills: ["Multi-Agent Architecture", "Streaming AI", "FastAPI / Next.js", "OCI Ollama"],
        description: "Deploy an end-to-end production AI system with self-hosted Llama 3.2 inference, vector memory, and streaming UI.",
        projectTask: "Deploy a complete multi-modal AI research assistant with automated citations and downloadable executive briefs.",
        resources: [
          { title: "OpenAI Cookbook / Llama Recipes", url: "https://github.com", type: "doc", provider: "Open Source Community", isFree: true },
        ],
      },
    ],
  },
  {
    id: "cloud-devops",
    title: "Cloud, DevOps & Systems",
    badge: "High Stability & Enterprise Roles",
    targetRoles: ["Cloud Engineer", "DevOps Specialist", "Site Reliability Engineer (SRE)"],
    description: "Linux systems engineering, containerization with Docker, CI/CD automation, Kubernetes clusters, and zero-cost cloud architecture on Oracle Cloud & Cloudflare.",
    nodes: [
      {
        id: "linux-bash",
        title: "Linux & Shell Scripting",
        subtitle: "Kernel, Permissions & CLI",
        category: "Operating Systems",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 18,
        matchedJobsCount: 19,
        skills: ["Linux", "Bash", "SSH", "Systemd"],
        description: "Master POSIX pipes, user permissions, process signals, systemd service management, networking tools (curl, netstat), and cron jobs.",
        projectTask: "Write an automated server health monitor script that alerts via Discord webhook on high CPU/disk spikes.",
        resources: [
          { title: "Linux Journey: Practical System Admin", url: "https://linuxjourney.com", type: "doc", provider: "Linux Community", isFree: true },
        ],
      },
      {
        id: "git-workflow",
        title: "Git Mastery & CI",
        subtitle: "Version Control & Branching",
        category: "Tooling",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["linux-bash"],
        estimatedHours: 15,
        matchedJobsCount: 24,
        skills: ["Git", "GitHub Actions", "Trunk-Based Development"],
        description: "Interactive rebase, merge conflict resolution, cherry-picking, semantic versioning, and pre-commit linting hooks.",
        projectTask: "Configure a monorepo with automated semantic release, changelog generator, and lint workflows on every PR.",
        resources: [
          { title: "Pro Git Official Book", url: "https://git-scm.com/book/en/v2", type: "doc", provider: "Scott Chacon", isFree: true },
        ],
      },
      {
        id: "docker-containers",
        title: "Docker & Containerization",
        subtitle: "Multi-Stage Builds & Isolation",
        category: "Containers",
        level: "Intermediate",
        x: 660,
        y: 180,
        dependencies: ["git-workflow"],
        estimatedHours: 25,
        matchedJobsCount: 26,
        skills: ["Docker", "Docker Compose", "Alpine Images"],
        description: "Write production multi-stage Dockerfiles, minimize image layers, isolate container networks, and orchestrate with Docker Compose.",
        projectTask: "Dockerize a full-stack Next.js + PostgreSQL + Redis application with healthchecks and persistent volumes.",
        resources: [
          { title: "Docker Official Getting Started Guide", url: "https://docs.docker.com/get-started", type: "doc", provider: "Docker Inc", isFree: true },
        ],
      },
      {
        id: "oci-cloud-infra",
        title: "OCI & Cloudflare Architecture",
        subtitle: "Zero-Cost Cloud Hosting",
        category: "Cloud",
        level: "Advanced",
        x: 960,
        y: 90,
        dependencies: ["docker-containers"],
        estimatedHours: 20,
        matchedJobsCount: 17,
        skills: ["Oracle Cloud Infrastructure", "Cloudflare DNS", "SSL / TLS", "Nginx"],
        description: "Provision ARM compute instances, configure virtual cloud networks (VCN), security ingress rules, SSL certificates, and reverse proxies.",
        projectTask: "Deploy a live production Docker stack on OCI Always Free ARM VM with automatic Let's Encrypt SSL.",
        resources: [
          { title: "Oracle Cloud Architecture Guide", url: "https://oracle.com/cloud", type: "doc", provider: "Oracle Devs", isFree: true },
        ],
      },
      {
        id: "k8s-orchestration",
        title: "Kubernetes & Pods",
        subtitle: "Clustering & Service Discovery",
        category: "Orchestration",
        level: "Advanced",
        x: 960,
        y: 270,
        dependencies: ["docker-containers"],
        estimatedHours: 35,
        matchedJobsCount: 21,
        skills: ["Kubernetes", "K3s / Minikube", "Deployments", "Ingress"],
        description: "Understand the control plane, pods, replica sets, cluster IP services, ingress controllers, config maps, and persistent volume claims.",
        projectTask: "Deploy a microservice application on local K3s with rolling updates and zero-downtime restarts.",
        resources: [
          { title: "Kubernetes The Hard Way", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way", type: "course", provider: "Kelsey Hightower", isFree: true },
        ],
      },
      {
        id: "ci-cd-pipelines",
        title: "CI/CD & Infrastructure as Code",
        subtitle: "Automated Deployments",
        category: "Automation",
        level: "Advanced",
        x: 1260,
        y: 180,
        dependencies: ["oci-cloud-infra", "k8s-orchestration"],
        estimatedHours: 30,
        matchedJobsCount: 23,
        skills: ["GitHub Actions", "Terraform", "Zero-Downtime Deployment"],
        description: "Write declarative Terraform configurations, build automated CI/CD pipelines with rollback capabilities, and canary releases.",
        projectTask: "Build an automated pipeline that builds a Docker image on PR merge, pushes to registry, and deploys via SSH to VM.",
        resources: [
          { title: "Learn Terraform by HashiCorp", url: "https://developer.hashicorp.com/terraform/tutorials", type: "doc", provider: "HashiCorp", isFree: true },
        ],
      },
      {
        id: "devops-capstone",
        title: "Self-Healing Cloud Infrastructure",
        subtitle: "Production Reliability Capstone",
        category: "Capstone",
        level: "Capstone",
        x: 1560,
        y: 180,
        dependencies: ["ci-cd-pipelines"],
        estimatedHours: 40,
        matchedJobsCount: 25,
        skills: ["SRE Principles", "Prometheus & Grafana", "Automated Failover"],
        description: "Deploy a monitored, self-healing production environment with Prometheus metrics, Grafana dashboards, and automated failover.",
        projectTask: "Deliver a monitored high-availability cluster with automated alerts, rate limiting, and 99.9% uptime validation.",
        resources: [
          { title: "Google SRE Book", url: "https://sre.google/sre-book/table-of-contents", type: "doc", provider: "Google Engineering", isFree: true },
        ],
      },
    ],
  },
];