export interface CanvasNodeResource {
  title: string;
  url: string;
  type: "video" | "doc" | "course" | "exercise";
  provider: string;
  isFree: boolean;
}

export interface CanvasNode {
  id: string;
  title: string;
  subtitle: string;
  category: string;
  level: "Foundational" | "Intermediate" | "Advanced" | "Capstone";
  x: number;
  y: number;
  dependencies: string[];
  estimatedHours: number;
  matchedJobsCount: number;
  skills: string[];
  keyTopics: string[];
  description: string;
  projectTask: string;
  mentalModelSnippet?: string;
  matchedCourseId?: string;
  resources: CanvasNodeResource[];
}

export interface CanvasTrack {
  id: string;
  title: string;
  badge: string;
  targetRoles: string[];
  description: string;
  nodes: CanvasNode[];
}

export const CANVAS_TRACKS: CanvasTrack[] = [
  {
    id: "ai-engineer-2026",
    title: "AI Engineer & LLM Systems (2026 Roadmap)",
    badge: "Most In-Demand • Highest Salary Potential",
    targetRoles: ["AI Engineer", "LLM Systems Developer", "Applied ML Specialist", "Agentic AI Architect"],
    description: "Complete 2026 learning path inspired by roadmap.sh & CampusX: from Vector Calculus and PyTorch Autograd to Transformers, LoRA, Advanced RAG, and Autonomous Multi-Agent Swarms.",
    nodes: [
      {
        id: "ai-math-foundations",
        title: "Mathematics for AI",
        subtitle: "Linear Algebra & Matrix Calculus",
        category: "Math & Tensors",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 20,
        matchedJobsCount: 34,
        skills: ["Linear Algebra", "Matrix Calculus", "Eigenvectors", "Probability & Bayes"],
        keyTopics: [
          "Dot products, projection & cosine similarity",
          "Matrix transformations, determinants & eigenvalues",
          "Multivariate gradient vectors & partial derivatives",
          "Chain rule of calculus & loss surface geometry",
        ],
        description: "Master the mathematical language of artificial intelligence. Understand why dot products measure semantic alignment, how matrix multiplications project embeddings, and how gradients navigate high-dimensional loss landscapes.",
        projectTask: "Write a pure NumPy script computing gradient vectors for a multi-variable loss function without automatic differentiation libraries.",
        mentalModelSnippet: "Gradient update: W = W - alpha * dL/dW\nDot product measures similarity: A · B = |A||B| cos(theta)\nAll attention projections: Q = X @ W_q, K = X @ W_k",
        matchedCourseId: "3b1b-dl",
        resources: [
          { title: "3Blue1Brown: Essence of Linear Algebra", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab", type: "video", provider: "3Blue1Brown", isFree: true },
          { title: "3Blue1Brown: Essence of Calculus", url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr", type: "video", provider: "3Blue1Brown", isFree: true },
          { title: "Stanford CS229: Linear Algebra Review", url: "https://cs229.stanford.edu/section/cs229-linalg.pdf", type: "doc", provider: "Stanford University", isFree: true },
        ],
      },
      {
        id: "ai-python-numpy",
        title: "Python Scientific Stack",
        subtitle: "NumPy Vectorization & SIMD",
        category: "Scientific Computing",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["ai-math-foundations"],
        estimatedHours: 25,
        matchedJobsCount: 42,
        skills: ["Python 3.12", "NumPy", "Pandas", "Vectorization", "Matplotlib"],
        keyTopics: [
          "NumPy array broadcasting mechanics and memory layouts",
          "Vectorized matrix math vs slow Python for-loops (50x speedup)",
          "Pandas DataFrames: groupby, window functions, handling nulls",
          "Exploratory data analysis & statistical visualization",
        ],
        description: "Modern AI requires computational fluency. Learn how NumPy utilizes BLAS/LAPACK and CPU SIMD registers to execute tensor multiplications at near C-speeds, and master tabular data wrangling with Pandas.",
        projectTask: "Benchmark matrix multiplication: compare raw Python nested loops against vectorized NumPy across 10,000x10,000 floats and plot memory scaling.",
        mentalModelSnippet: "import numpy as np\n# Vectorized SIMD operation (bypasses Python interpreter loop):\nresult = np.dot(matrix_a, matrix_b)\n# Broadcasting allows operations across mismatched dimensions:\nnormalized = (tensor - np.mean(tensor, axis=0)) / np.std(tensor, axis=0)",
        matchedCourseId: "angela-python",
        resources: [
          { title: "NumPy Official: Array Programming Guide", url: "https://numpy.org/doc/stable/user/basics.html", type: "doc", provider: "NumPy Devs", isFree: true },
          { title: "Harvard CS50P: Python for Data Science", url: "https://cs50.harvard.edu/python", type: "course", provider: "Harvard University", isFree: true },
        ],
      },
      {
        id: "ai-classical-ml",
        title: "Classical Machine Learning",
        subtitle: "Scikit-Learn & Feature Engineering",
        category: "Machine Learning",
        level: "Intermediate",
        x: 660,
        y: 80,
        dependencies: ["ai-python-numpy"],
        estimatedHours: 35,
        matchedJobsCount: 38,
        skills: ["Scikit-Learn", "XGBoost", "Cross-Validation", "ROC-AUC", "Feature Pipelines"],
        keyTopics: [
          "Supervised learning: Linear/Logistic Regression, Decision Trees, Ensembles",
          "Gradient Boosted Trees (XGBoost, LightGBM, CatBoost)",
          "Bias-Variance tradeoff, overfitting & L1/L2 regularization",
          "Preventing data leakage with Scikit-Learn Pipelines & StratifiedKFold",
        ],
        description: "Before deep learning, classical ML remains the workhorse of 80% of enterprise production systems. Master feature engineering, hyperparameter tuning, and metric evaluation (Precision/Recall vs ROC-AUC).",
        projectTask: "Train an XGBoost credit risk model with 5-fold cross-validation, feature importance attribution, and a zero-data-leakage pipeline.",
        mentalModelSnippet: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom xgboost import XGBClassifier\n# Invariant: Never fit transforms on test data\npipe = Pipeline([('scaler', StandardScaler()), ('model', XGBClassifier())])\npipe.fit(X_train, y_train)",
        matchedCourseId: "krish-genai",
        resources: [
          { title: "CampusX: 100 Days of Machine Learning", url: "https://www.youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLujYhhW", type: "video", provider: "CampusX", isFree: true },
          { title: "StatQuest: Machine Learning Fundamentals", url: "https://www.youtube.com/c/joshstarmer", type: "video", provider: "StatQuest", isFree: true },
        ],
      },
      {
        id: "ai-micrograd-autograd",
        title: "Autograd Engine from Scratch",
        subtitle: "Reverse-Mode Auto-Diff & DAG",
        category: "Deep Learning Foundations",
        level: "Intermediate",
        x: 660,
        y: 280,
        dependencies: ["ai-python-numpy"],
        estimatedHours: 20,
        matchedJobsCount: 29,
        skills: ["Backpropagation", "Computational Graph", "Micrograd", "Chain Rule", "Perceptron"],
        keyTopics: [
          "Building a scalar-valued autograd engine (Micrograd) from scratch",
          "Representing expressions as Directed Acyclic Graphs (DAG)",
          "Topological sorting for automated reverse-mode backpropagation",
          "Training a Multi-Layer Perceptron (MLP) on binary classification",
        ],
        description: "Andrej Karpathy's foundational milestone. Strip away the magic of PyTorch: implement every addition, multiplication, ReLU, and backprop derivative in raw Python to build an intuitive mental model of neural learning.",
        projectTask: "Build a micrograd autograd engine from scratch supporting tanh, relu, and pow operations, then train a 2-layer MLP to solve XOR.",
        mentalModelSnippet: "class Value:\n  def backward(self):\n    topo = []\n    visited = set()\n    def build_topo(v):\n      if v not in visited:\n        visited.add(v)\n        for child in v._prev: build_topo(child)\n        topo.append(v)\n    build_topo(self)\n    self.grad = 1.0\n    for node in reversed(topo): node._backward()",
        matchedCourseId: "karpathy-nn",
        resources: [
          { title: "Andrej Karpathy: Building Micrograd", url: "https://www.youtube.com/watch?v=VMj-3S1tku0", type: "video", provider: "Andrej Karpathy", isFree: true },
          { title: "karpathy/micrograd GitHub Repo", url: "https://github.com/karpathy/micrograd", type: "exercise", provider: "Open Source", isFree: true },
        ],
      },
      {
        id: "ai-pytorch-cuda",
        title: "PyTorch & GPU Acceleration",
        subtitle: "Tensors, nn.Module & Mixed Precision",
        category: "Deep Learning Engineering",
        level: "Intermediate",
        x: 960,
        y: 180,
        dependencies: ["ai-classical-ml", "ai-micrograd-autograd"],
        estimatedHours: 35,
        matchedJobsCount: 45,
        skills: ["PyTorch", "CUDA", "nn.Module", "AdamW", "bfloat16", "DataLoader"],
        keyTopics: [
          "Tensor manipulation, reshaping, slicing, and CUDA memory management",
          "Subclassing nn.Module, custom forward passes & loss functions",
          "PyTorch Dataset & DataLoader with multi-worker prefetching",
          "Mixed precision training with torch.cuda.amp and bfloat16",
        ],
        description: "Transition from educational scalar engines to production industrial deep learning. Master PyTorch tensor operations, CUDA device management, and write modular neural network layers.",
        projectTask: "Implement and train a deep convolutional neural net or residual MLP on CIFAR-10 with custom learning rate scheduling and early stopping.",
        mentalModelSnippet: "import torch\nimport torch.nn as nn\ndevice = 'cuda' if torch.cuda.is_available() else 'cpu'\n# Automatic Mixed Precision for 2x faster GPU throughput:\nwith torch.autocast(device_type=device, dtype=torch.bfloat16):\n  logits = model(inputs)\n  loss = criterion(logits, targets)\nscaler.scale(loss).backward()",
        matchedCourseId: "karpathy-nn",
        resources: [
          { title: "Fast.ai: Practical Deep Learning for Coders", url: "https://course.fast.ai", type: "course", provider: "Fast.ai", isFree: true },
          { title: "PyTorch Official Tutorials", url: "https://pytorch.org/tutorials", type: "doc", provider: "PyTorch Team", isFree: true },
        ],
      },
      {
        id: "ai-transformers-attention",
        title: "Transformers & Attention Mechanism",
        subtitle: "Self-Attention, RoPE & KV Cache",
        category: "Transformer Architecture",
        level: "Advanced",
        x: 1260,
        y: 80,
        dependencies: ["ai-pytorch-cuda"],
        estimatedHours: 40,
        matchedJobsCount: 52,
        skills: ["Attention Is All You Need", "Self-Attention", "RoPE", "KV Cache", "nanoGPT"],
        keyTopics: [
          "Scaled Dot-Product Attention: Attention(Q, K, V) = softmax(QK^T / sqrt(d_k))V",
          "Multi-Head Attention (MHA) vs Grouped-Query Attention (GQA)",
          "Rotary Position Embeddings (RoPE) and RMSNorm normalization",
          "Key-Value (KV) cache mechanics in autoregressive token generation",
        ],
        description: "The core architectural breakthrough powering modern AI. Understand self-attention intuitively, implement causal masking so tokens only look backward in time, and build a GPT-2 decoder from scratch.",
        projectTask: "Build Andrej Karpathy's NanoGPT from raw PyTorch: train a 10M parameter character-level transformer on Shakespeare with text generation.",
        mentalModelSnippet: "# Scaled Dot-Product Causal Self-Attention:\nB, T, C = x.shape\nq, k, v = self.q_proj(x), self.k_proj(x), self.v_proj(x)\natt = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))\natt = att.masked_fill(self.bias[:,:,:T,:T] == 0, float('-inf'))\natt = F.softmax(att, dim=-1)\ny = att @ v",
        matchedCourseId: "karpathy-nn",
        resources: [
          { title: "Andrej Karpathy: Let's build GPT from scratch", url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", type: "video", provider: "Andrej Karpathy", isFree: true },
          { title: "Attention Is All You Need (Paper)", url: "https://arxiv.org/abs/1706.03762", type: "doc", provider: "Google Research", isFree: true },
        ],
      },
      {
        id: "ai-llm-tokenizers",
        title: "Modern LLMs & Tokenization",
        subtitle: "BPE Tokenizers, Llama 3 & DeepSeek",
        category: "LLM Systems",
        level: "Advanced",
        x: 1260,
        y: 280,
        dependencies: ["ai-pytorch-cuda"],
        estimatedHours: 30,
        matchedJobsCount: 48,
        skills: ["BPE Tokenization", "Tiktoken", "Llama 3.2", "DeepSeek MoE", "Context Windows"],
        keyTopics: [
          "Byte-Pair Encoding (BPE) algorithm from scratch (minbpe)",
          "Tokenizer nuances: whitespace sensitivity, byte fallback, special tokens",
          "Modern LLM architectures: Llama 3 SwiGLU, DeepSeek-V3 Mixture of Experts",
          "Context length scaling: YaRN, RoPE frequency extrapolation for 128k context",
        ],
        description: "Tokenizers are where most LLM edge cases, hallucinations, and security flaws originate. Master how text converts into token IDs, how vocabulary compression works, and inspect modern open-weights architectures.",
        projectTask: "Implement a Byte-Pair Encoding tokenizer in Python that trains on custom corpus text and compresses raw bytes into 1,000 merged tokens.",
        mentalModelSnippet: "# Byte-Pair Encoding: find most frequent adjacent pair and merge\ndef get_stats(ids):\n  counts = {}\n  for pair in zip(ids, ids[1:]): counts[pair] = counts.get(pair, 0) + 1\n  return counts\n# Replace top pair with new unique token id",
        matchedCourseId: "karpathy-nn",
        resources: [
          { title: "Andrej Karpathy: Let's build the GPT Tokenizer", url: "https://www.youtube.com/watch?v=zduSFxRajkE", type: "video", provider: "Andrej Karpathy", isFree: true },
          { title: "karpathy/minbpe GitHub Repo", url: "https://github.com/karpathy/minbpe", type: "exercise", provider: "Open Source", isFree: true },
        ],
      },
      {
        id: "ai-finetuning-peft",
        title: "Fine-Tuning & Alignment",
        subtitle: "LoRA, QLoRA, SFT & DPO",
        category: "Fine-Tuning",
        level: "Advanced",
        x: 1560,
        y: 80,
        dependencies: ["ai-transformers-attention"],
        estimatedHours: 35,
        matchedJobsCount: 39,
        skills: ["LoRA", "QLoRA", "SFT", "DPO", "HuggingFace TRL", "bitsandbytes"],
        keyTopics: [
          "Low-Rank Adaptation (LoRA: W = W0 + B*A) with rank r=16",
          "4-bit NormalFloat (NF4) quantization with bitsandbytes (QLoRA)",
          "Supervised Fine-Tuning (SFT) on conversational instruction datasets",
          "Direct Preference Optimization (DPO) vs PPO/RLHF for human alignment",
        ],
        description: "Learn how to adapt multi-billion parameter foundation models to specialized tasks without multi-thousand dollar GPU clusters. Master parameter-efficient adapters (LoRA/QLoRA) and preference alignment.",
        projectTask: "Fine-tune an open-source Llama 3.2 3B or Qwen 2.5 model on a medical Q&A dataset using QLoRA inside a free Google Colab T4 GPU.",
        mentalModelSnippet: "from peft import LoraConfig, get_peft_model\n# Freeze 99% of base weights, train only rank-16 low-rank matrices A & B\nconfig = LoraConfig(r=16, lora_alpha=32, target_modules=['q_proj', 'v_proj'])\nmodel = get_peft_model(base_model, config)",
        matchedCourseId: "krish-genai",
        resources: [
          { title: "CampusX: LoRA & QLoRA Fine-Tuning Masterclass", url: "https://www.youtube.com/c/CampusX-official", type: "video", provider: "CampusX", isFree: true },
          { title: "Hugging Face TRL Alignment Guide", url: "https://huggingface.co/docs/trl", type: "doc", provider: "Hugging Face", isFree: true },
        ],
      },
      {
        id: "ai-rag-vectordb",
        title: "Production RAG & Vector DBs",
        subtitle: "HNSW Indexing, Hybrid & Re-ranking",
        category: "Information Retrieval",
        level: "Advanced",
        x: 1560,
        y: 280,
        dependencies: ["ai-llm-tokenizers"],
        estimatedHours: 35,
        matchedJobsCount: 64,
        skills: ["RAG Systems", "Qdrant", "Pinecone", "pgvector", "Hybrid Search", "Cohere Rerank"],
        keyTopics: [
          "Chunking strategies: Semantic chunking, sliding windows, parent-child docs",
          "Dense vector indexing: Hierarchical Navigable Small World (HNSW) graphs",
          "Hybrid search: Combining dense semantic vectors with BM25 sparse keyword ranking",
          "Cross-Encoder re-ranking (Cohere / BGE-Reranker) to eliminate hallucinations",
        ],
        description: "Retrieval-Augmented Generation is the #1 enterprise AI architecture. Learn how to ground LLM outputs in verified external documentation, prevent hallucinations, and implement sub-100ms hybrid search.",
        projectTask: "Build an authenticated multi-document financial RAG pipeline using pgvector/Qdrant with hybrid keyword+vector search and source citations.",
        mentalModelSnippet: "# Hybrid RAG retrieval pipeline:\ndense_hits = vector_db.search(query_embedding, limit=20)\nsparse_hits = bm25.search(query_text, limit=20)\nmerged = reciprocal_rank_fusion(dense_hits, sparse_hits)\nfinal_context = reranker.rerank(query, merged[:10])",
        matchedCourseId: "krish-genai",
        resources: [
          { title: "LangChain: RAG from Scratch Series", url: "https://www.youtube.com/playlist?list=PLfaIDF9894O4C2h62Lh9KOmv-Hkk9bI5j", type: "video", provider: "LangChain", isFree: true },
          { title: "Pinecone: Mastering Vector Search & HNSW", url: "https://www.pinecone.io/learn", type: "doc", provider: "Pinecone", isFree: true },
        ],
      },
      {
        id: "ai-inference-vllm",
        title: "Inference Systems & Serving",
        subtitle: "vLLM, PagedAttention & GGUF",
        category: "Inference & Systems",
        level: "Advanced",
        x: 1860,
        y: 80,
        dependencies: ["ai-finetuning-peft"],
        estimatedHours: 30,
        matchedJobsCount: 36,
        skills: ["vLLM", "PagedAttention", "GGUF", "llama.cpp", "TensorRT-LLM", "Speculative Decoding"],
        keyTopics: [
          "KV cache memory bottleneck and fragmentation in high-concurrency serving",
          "PagedAttention (vLLM) managing KV cache like virtual operating system memory pages",
          "Model quantization formats: AWQ (Activation-aware), GPTQ, and GGUF for edge CPU/Metal",
          "Speculative decoding: small draft model predicts tokens verified in parallel by large model",
        ],
        description: "Deploying models to production requires understanding hardware latency and VRAM constraints. Learn how vLLM achieves 20x higher throughput via PagedAttention and continuous batching.",
        projectTask: "Self-host an open-source LLM using vLLM on an OCI GPU or local llama.cpp instance, benchmarking requests-per-second and tokens-per-second.",
        mentalModelSnippet: "# vLLM serving with PagedAttention continuous batching:\nfrom vllm import LLM, SamplingParams\nllm = LLM(model='meta-llama/Llama-3.2-3B', tensor_parallel_size=1)\nprompts = ['Explain backprop in 1 sentence:', 'Write a quicksort in Python:']\noutputs = llm.generate(prompts, SamplingParams(temperature=0.7, max_tokens=150))",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "vLLM: High-Throughput Serving Architecture", url: "https://docs.vllm.ai", type: "doc", provider: "UC Berkeley / vLLM", isFree: true },
          { title: "llama.cpp & GGUF Format Deep Dive", url: "https://github.com/ggerganov/llama.cpp", type: "doc", provider: "Open Source", isFree: true },
        ],
      },
      {
        id: "ai-agentic-systems",
        title: "Autonomous Agents & Tool-Use",
        subtitle: "LangGraph, ReAct & MCP Protocol",
        category: "Agentic AI",
        level: "Advanced",
        x: 1860,
        y: 280,
        dependencies: ["ai-rag-vectordb"],
        estimatedHours: 40,
        matchedJobsCount: 58,
        skills: ["LangGraph", "Function Calling", "ReAct Loops", "Anthropic MCP", "Multi-Agent"],
        keyTopics: [
          "ReAct (Reasoning + Acting) decision loops with native JSON tool calling",
          "Stateful multi-agent workflows using LangGraph cyclic state graphs",
          "Anthropic Model Context Protocol (MCP) for standardized tool interoperability",
          "Agent memory persistence, human-in-the-loop validation, and infinite loop guardrails",
        ],
        description: "2026 is the era of Agentic AI. Move beyond static chatbots to autonomous agents that can plan multi-step workflows, call SQL/bash tools, inspect GitHub repositories, and correct their own errors.",
        projectTask: "Build a multi-agent software engineer using LangGraph: Planner Agent breaks down tasks, Coder Agent writes tests, and Tester Agent executes code in sandbox.",
        mentalModelSnippet: "from langgraph.graph import StateGraph, END\nworkflow = StateGraph(AgentState)\nworkflow.add_node('planner', plan_step)\nworkflow.add_node('executor', run_tools)\nworkflow.add_conditional_edges('executor', should_continue, {'continue': 'executor', 'done': END})",
        matchedCourseId: "krish-genai",
        resources: [
          { title: "DeepLearning.AI: Multi-Agent Workflows with LangGraph", url: "https://www.deeplearning.ai/short-courses", type: "course", provider: "DeepLearning.AI", isFree: true },
          { title: "Model Context Protocol (MCP) Specification", url: "https://modelcontextprotocol.io", type: "doc", provider: "Anthropic", isFree: true },
        ],
      },
      {
        id: "ai-eval-guardrails",
        title: "Evaluation & LLM Guardrails",
        subtitle: "Ragas, Tracing & OWASP Defense",
        category: "MLOps & Security",
        level: "Advanced",
        x: 2160,
        y: 180,
        dependencies: ["ai-inference-vllm", "ai-agentic-systems"],
        estimatedHours: 25,
        matchedJobsCount: 41,
        skills: ["Ragas", "OpenTelemetry", "Langfuse", "Prompt Injection Defense", "OWASP Top 10 LLM"],
        keyTopics: [
          "RAG Triad evaluation: Faithfulness, Answer Relevance, Context Precision with Ragas",
          "Hardening against Prompt Injections, jailbreaks, and indirect data exfiltration",
          "OpenTelemetry tracing of tokens, latencies, and tool calls using Langfuse",
          "Canary tokens, input guardrails & toxic language filtering",
        ],
        description: "AI without automated evaluation is just guessing. Learn how to benchmark generative outputs using LLM-as-a-Judge, trace production conversations with OpenTelemetry, and secure applications against OWASP Top 10 LLM vulnerabilities.",
        projectTask: "Build an automated evaluation suite using Ragas that scores a 50-question RAG benchmark on Faithfulness and flags prompt injection attempts.",
        mentalModelSnippet: "from ragas import evaluate\nfrom ragas.metrics import faithfulness, answer_relevancy\n# Automated continuous LLM testing in CI/CD pipeline:\nscores = evaluate(dataset=evaluation_dataset, metrics=[faithfulness, answer_relevancy])\nassert scores['faithfulness'] > 0.85, 'Model hallucination rate exceeds safety limit!'",
        matchedCourseId: "krish-genai",
        resources: [
          { title: "Ragas: Automated Evaluation of RAG", url: "https://docs.ragas.io", type: "doc", provider: "Ragas Team", isFree: true },
          { title: "OWASP Top 10 for Large Language Models", url: "https://owasp.org/www-project-top-10-for-large-language-model-applications", type: "doc", provider: "OWASP", isFree: true },
        ],
      },
      {
        id: "ai-capstone-system",
        title: "Autonomous AI Engineer Capstone",
        subtitle: "Production Multi-Agent RAG System",
        category: "Production Capstone",
        level: "Capstone",
        x: 2460,
        y: 180,
        dependencies: ["ai-eval-guardrails"],
        estimatedHours: 50,
        matchedJobsCount: 72,
        skills: ["Production AI System", "LangGraph", "Qdrant", "vLLM / Groq", "Next.js Streaming", "Docker"],
        keyTopics: [
          "Architecting an end-to-end multi-agent AI research assistant with live web and vector search",
          "Low-latency streaming responses with Server-Sent Events (SSE) and token buffering",
          "Containerized deployment with Docker Compose on cloud VM with automated healthchecks",
          "Full test suite, Ragas evaluation score, and public GitHub Proof-of-Work repository",
        ],
        description: "The ultimate portfolio proof-of-work. Build, evaluate, containerize, and deploy a complete production AI application that recruiters can test live.",
        projectTask: "Deploy an Autonomous Developer Agent with live streaming SSE UI, vector search over documentation, GitHub PR review tools, and automated Ragas evaluation benchmarks.",
        mentalModelSnippet: "# Dockerized Production Architecture:\n# Frontend: Next.js 15 App Router (Streaming Markdown)\n# Backend: FastAPI + LangGraph State Engine\n# Retrieval: Qdrant Vector DB with Hybrid HNSW\n# Serving: Groq API / Self-Hosted vLLM Llama 3.2",
        matchedCourseId: "karpathy-nn",
        resources: [
          { title: "Role Nest Capstone Blueprint Guide", url: "https://github.com", type: "exercise", provider: "Role Nest Academy", isFree: true },
          { title: "OpenAI Cookbook Production Architecture", url: "https://github.com/openai/openai-cookbook", type: "doc", provider: "OpenAI", isFree: true },
        ],
      },
    ],
  },
  {
    id: "fullstack-web",
    title: "Full-Stack Web Engineering",
    badge: "Most In-Demand (India & Global Remote)",
    targetRoles: ["Full Stack Developer", "Frontend Engineer", "Next.js Specialist"],
    description: "Master modern web development from semantic HTML & TypeScript through Next.js 15, PostgreSQL, and scalable Cloudflare edge infrastructure.",
    nodes: [
      {
        id: "web-foundations",
        title: "Web Foundations",
        subtitle: "HTML5 & CSS3 Standards",
        category: "Frontend",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 15,
        matchedJobsCount: 18,
        skills: ["HTML", "CSS", "Responsive Design"],
        keyTopics: ["Semantic HTML landmarks", "Flexbox & CSS Grid layouts", "ARIA accessibility standards", "Mobile-first responsive design"],
        description: "Master semantic markup, flexbox, CSS grid, accessible ARIA landmarks, and mobile-first responsive layouts.",
        projectTask: "Build an accessible, responsive developer portfolio with dark/light themes without JavaScript frameworks.",
        mentalModelSnippet: "/* Responsive Grid Layout */\n.grid-container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n  gap: 1.5rem;\n}",
        matchedCourseId: "traversy-modern-web",
        resources: [
          { title: "MDN Web Docs: HTML & CSS", url: "https://developer.mozilla.org", type: "doc", provider: "MDN", isFree: true },
          { title: "CS50 Web Programming: HTML & CSS", url: "https://cs50.harvard.edu/web", type: "course", provider: "Harvard CS50", isFree: true },
        ],
      },
      {
        id: "js-core",
        title: "Modern JavaScript",
        subtitle: "ES2024 & Asynchronous Flow",
        category: "Core Language",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["web-foundations"],
        estimatedHours: 25,
        matchedJobsCount: 26,
        skills: ["JavaScript", "Promises", "Event Loop", "DOM APIs"],
        keyTopics: ["Execution context & closures", "Event Loop microtasks vs macrotasks", "Async/await & Promise.allSettled", "Functional array transformations"],
        description: "Deep dive into execution context, closures, event loop microtasks, async/await, and functional programming constructs.",
        projectTask: "Build a client-side search engine with debouncing, localStorage caching, and infinite scrolling.",
        mentalModelSnippet: "// Debounce utility with closure:\nfunction debounce(fn, delayMs) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delayMs);\n  };\n}",
        matchedCourseId: "traversy-modern-web",
        resources: [
          { title: "JavaScript.info: Modern Tutorial", url: "https://javascript.info", type: "doc", provider: "Open Book", isFree: true },
          { title: "Namaste JavaScript (Season 1 & 2)", url: "https://www.youtube.com/playlist?list=PLlasXeu85E9cQ32gLCvAvr9vNaUccPVNP", type: "video", provider: "Akshay Saini", isFree: true },
        ],
      },
      {
        id: "ts-mastery",
        title: "TypeScript Strict",
        subtitle: "Type Safety & Interfaces",
        category: "Type System",
        level: "Intermediate",
        x: 660,
        y: 90,
        dependencies: ["js-core"],
        estimatedHours: 20,
        matchedJobsCount: 22,
        skills: ["TypeScript", "Generics", "Zod Validation"],
        keyTopics: ["Zero-any strict compiler flags", "Generic constraints & utility types", "Discriminated union states", "Runtime validation with Zod schemas"],
        description: "Enforce zero-any policies, master union types, generic constraints, conditional types, and runtime schema validation with Zod.",
        projectTask: "Build a strictly typed REST client with Zod request/response contracts and discriminated unions.",
        mentalModelSnippet: "import { z } from 'zod';\nconst UserSchema = z.object({\n  id: z.string().uuid(),\n  email: z.string().email(),\n  role: z.enum(['ADMIN', 'USER'])\n});\ntype User = z.infer<typeof UserSchema>;",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "Total TypeScript Essentials", url: "https://totaltypescript.com", type: "course", provider: "Matt Pocock", isFree: true },
          { title: "TypeScript Official Handbook", url: "https://typescriptlang.org/docs", type: "doc", provider: "Microsoft", isFree: true },
        ],
      },
      {
        id: "react-ecosystem",
        title: "React 19 & Architecture",
        subtitle: "Component Lifecycle & State",
        category: "Frontend",
        level: "Intermediate",
        x: 660,
        y: 270,
        dependencies: ["js-core"],
        estimatedHours: 30,
        matchedJobsCount: 29,
        skills: ["React", "Custom Hooks", "Context API"],
        keyTopics: ["Virtual DOM reconciliation & fiber", "Custom hooks & state boundaries", "React 19 useActionState & useOptimistic", "Rendering performance & memoization"],
        description: "Learn reconciliation, concurrent features, custom hooks, atomic component boundaries, and render memoization.",
        projectTask: "Build an interactive Kanban board with drag-and-drop state, optimistic UI updates, and undo/redo history.",
        mentalModelSnippet: "// Custom state hook with local persistence:\nfunction usePersistedState<T>(key: string, initial: T) {\n  const [val, setVal] = useState<T>(() => {\n    const saved = localStorage.getItem(key);\n    return saved ? JSON.parse(saved) : initial;\n  });\n  // synchronize on change...\n  return [val, setVal] as const;\n}",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "React Official Interactive Docs", url: "https://react.dev", type: "doc", provider: "React Team", isFree: true },
          { title: "Full Stack Open: React Section", url: "https://fullstackopen.com/en", type: "course", provider: "Univ of Helsinki", isFree: true },
        ],
      },
      {
        id: "tailwind-styling",
        title: "Tailwind CSS & UI",
        subtitle: "Design Systems & Radix",
        category: "Design",
        level: "Intermediate",
        x: 960,
        y: 90,
        dependencies: ["ts-mastery", "react-ecosystem"],
        estimatedHours: 12,
        matchedJobsCount: 16,
        skills: ["Tailwind CSS", "shadcn/ui", "Radix Primitives"],
        keyTopics: ["Utility-first design tokens", "shadcn/ui component integration", "Radix headless accessible primitives", "Dark mode CSS variable theming"],
        description: "Create accessible design systems using utility-first CSS, component tokens, animation transitions, and headless primitives.",
        projectTask: "Design and implement a responsive analytics dashboard with animated charts and dark-mode tokens.",
        mentalModelSnippet: "<button className=\"inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 font-bold text-white transition-all hover:bg-emerald-500 active:scale-95 shadow-sm\">\n  Action\n</button>",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "Tailwind CSS Documentation", url: "https://tailwindcss.com/docs", type: "doc", provider: "Tailwind Labs", isFree: true },
        ],
      },
      {
        id: "nextjs-fullstack",
        title: "Next.js 15 App Router",
        subtitle: "Server Components & Edge",
        category: "Full Stack",
        level: "Advanced",
        x: 960,
        y: 270,
        dependencies: ["react-ecosystem"],
        estimatedHours: 35,
        matchedJobsCount: 28,
        skills: ["Next.js", "Server Actions", "Turborepo"],
        keyTopics: ["React Server Components (RSC) vs Client", "Server Actions with zero client bundle impact", "Dynamic caching & revalidateTag strategies", "Edge Middleware & Streaming SSR"],
        description: "Master React Server Components (RSC), dynamic caching strategies, Server Actions, streaming SSR, and edge middleware.",
        projectTask: "Build an authenticated multi-tenant CMS with server actions, optimistic mutations, and SEO metadata.",
        mentalModelSnippet: "// Server Action inside Next.js 15 App Router:\n'use server';\nexport async function updateProfile(formData: FormData) {\n  const session = await auth();\n  if (!session) throw new Error('Unauthorized');\n  await db.update(users).set({ name: formData.get('name') });\n  revalidatePath('/profile');\n}",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "Next.js Official Learn Course", url: "https://nextjs.org/learn", type: "course", provider: "Vercel", isFree: true },
        ],
      },
      {
        id: "database-backend",
        title: "PostgreSQL & Drizzle",
        subtitle: "Relational Modeling & ORM",
        category: "Backend",
        level: "Advanced",
        x: 1260,
        y: 180,
        dependencies: ["nextjs-fullstack", "tailwind-styling"],
        estimatedHours: 25,
        matchedJobsCount: 24,
        skills: ["PostgreSQL", "Drizzle ORM", "Redis", "Cloudflare R2"],
        keyTopics: ["Relational schemas & foreign key constraints", "ACID transactions & row-level locking", "Drizzle schema migrations & TypeScript inference", "Redis caching & rate limiting"],
        description: "Design relational database schemas, indexes, foreign keys, migrations, transactions, and Redis distributed caching.",
        projectTask: "Implement a transactional booking system with row-level locking, automated migrations, and audit logging.",
        mentalModelSnippet: "import { pgTable, text, timestamp } from 'drizzle-orm/pg-core';\nexport const users = pgTable('users', {\n  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),\n  email: text('email').notNull().unique(),\n  createdAt: timestamp('created_at').defaultNow().notNull()\n});",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "PostgreSQL Tutorial for Beginners", url: "https://postgresqltutorial.com", type: "doc", provider: "PostgreSQL Guide", isFree: true },
          { title: "Drizzle ORM Official Guide", url: "https://orm.drizzle.team", type: "doc", provider: "Drizzle Team", isFree: true },
        ],
      },
      {
        id: "web-capstone",
        title: "Full-Stack SaaS Capstone",
        subtitle: "Production Deployment",
        category: "Capstone",
        level: "Capstone",
        x: 1560,
        y: 180,
        dependencies: ["database-backend"],
        estimatedHours: 40,
        matchedJobsCount: 31,
        skills: ["Full Stack Architecture", "Auth.js", "Cloudflare Pages", "OCI Deployment"],
        keyTopics: ["Multi-tenant architecture", "Production OAuth security", "Automated GitHub Actions CI/CD", "Monitoring and SSL termination"],
        description: "Build, test, and deploy a complete production web platform with authentication, database persistence, and background jobs.",
        projectTask: "Ship a complete SaaS product with GitHub OAuth, transactional email, stripe mock or real payments, and live custom domain.",
        mentalModelSnippet: "# Deployment Checklist:\n# 1. Zero-downtime database migrations\n# 2. Security headers (HSTS, CSP, X-Frame-Options)\n# 3. Environment secrets separation (Dev vs Prod)",
        matchedCourseId: "hitesh-chai-fullstack",
        resources: [
          { title: "SaaS Boilerplate Guide", url: "https://github.com", type: "exercise", provider: "Role Nest Academy", isFree: true },
        ],
      },
    ],
  },
  {
    id: "cloud-devops",
    title: "Cloud, DevOps & Systems",
    badge: "High Stability & Enterprise Roles",
    targetRoles: ["Cloud Engineer", "DevOps Specialist", "Site Reliability Engineer (SRE)"],
    description: "Linux systems engineering, containerization with Docker, CI/CD automation, Kubernetes clusters, and zero-cost cloud architecture on Oracle Cloud & Cloudflare.",
    nodes: [
      {
        id: "linux-bash",
        title: "Linux & Shell Scripting",
        subtitle: "Kernel, Permissions & CLI",
        category: "Operating Systems",
        level: "Foundational",
        x: 60,
        y: 180,
        dependencies: [],
        estimatedHours: 18,
        matchedJobsCount: 19,
        skills: ["Linux", "Bash", "SSH", "Systemd"],
        keyTopics: ["POSIX pipes, redirections & streams", "User permissions (chmod/chown) & sudoers", "Systemd unit services & daemon management", "Networking CLI tools (curl, ss, iptables)"],
        description: "Master POSIX pipes, user permissions, process signals, systemd service management, networking tools (curl, netstat), and cron jobs.",
        projectTask: "Write an automated server health monitor script that alerts via Discord webhook on high CPU/disk spikes.",
        mentalModelSnippet: "#!/usr/bin/env bash\n# Monitor disk usage and alert when above 85%\nUSAGE=$(df -h / | awk 'NR==2 {print $5}' | tr -d '%')\nif [ \"$USAGE\" -gt 85 ]; then\n  echo \"Disk critical: $USAGE%\"\nfi",
        matchedCourseId: "networkchuck-linux",
        resources: [
          { title: "Linux Journey: Practical System Admin", url: "https://linuxjourney.com", type: "doc", provider: "Linux Community", isFree: true },
        ],
      },
      {
        id: "git-workflow",
        title: "Git Mastery & CI",
        subtitle: "Version Control & Branching",
        category: "Tooling",
        level: "Foundational",
        x: 360,
        y: 180,
        dependencies: ["linux-bash"],
        estimatedHours: 15,
        matchedJobsCount: 24,
        skills: ["Git", "GitHub Actions", "Trunk-Based Development"],
        keyTopics: ["Interactive rebasing & merge strategies", "Resolving complex merge conflicts", "Semantic versioning & release tags", "Pre-commit linting & formatting hooks"],
        description: "Interactive rebase, merge conflict resolution, cherry-picking, semantic versioning, and pre-commit linting hooks.",
        projectTask: "Configure a monorepo with automated semantic release, changelog generator, and lint workflows on every PR.",
        mentalModelSnippet: "# Interactive rebase to clean up commits:\ngit rebase -i HEAD~4\n# Cherry-pick hotfix into production branch:\ngit cherry-pick <commit-sha>",
        matchedCourseId: "striver-a2z-dsa",
        resources: [
          { title: "Pro Git Official Book", url: "https://git-scm.com/book/en/v2", type: "doc", provider: "Scott Chacon", isFree: true },
        ],
      },
      {
        id: "docker-containers",
        title: "Docker & Containerization",
        subtitle: "Multi-Stage Builds & Isolation",
        category: "Containers",
        level: "Intermediate",
        x: 660,
        y: 180,
        dependencies: ["git-workflow"],
        estimatedHours: 25,
        matchedJobsCount: 26,
        skills: ["Docker", "Docker Compose", "Alpine Images"],
        keyTopics: ["Multi-stage Dockerfiles minimizing image size", "Layer caching & avoiding rebuilds", "Docker network bridge isolation", "Container healthchecks & restart policies"],
        description: "Write production multi-stage Dockerfiles, minimize image layers, isolate container networks, and orchestrate with Docker Compose.",
        projectTask: "Dockerize a full-stack Next.js + PostgreSQL + Redis application with healthchecks and persistent volumes.",
        mentalModelSnippet: "# Production Multi-Stage Dockerfile:\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml ./\nRUN pnpm install --frozen-lockfile\nCOPY . .\nRUN pnpm build\n\nFROM node:20-alpine AS runner\nWORKDIR /app\nCOPY --from=builder /app/.next/standalone ./\nCMD [\"node\", \"server.js\"]",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "Docker Official Getting Started Guide", url: "https://docs.docker.com/get-started", type: "doc", provider: "Docker Inc", isFree: true },
        ],
      },
      {
        id: "oci-cloud-infra",
        title: "OCI & Cloudflare Architecture",
        subtitle: "Zero-Cost Cloud Hosting",
        category: "Cloud",
        level: "Advanced",
        x: 960,
        y: 90,
        dependencies: ["docker-containers"],
        estimatedHours: 20,
        matchedJobsCount: 17,
        skills: ["Oracle Cloud Infrastructure", "Cloudflare DNS", "SSL / TLS", "Nginx"],
        keyTopics: ["Provisioning ARM Ampere compute instances", "Virtual Cloud Network (VCN) security lists", "Reverse proxying with Nginx", "Automated Let's Encrypt SSL certificates"],
        description: "Provision ARM compute instances, configure virtual cloud networks (VCN), security ingress rules, SSL certificates, and reverse proxies.",
        projectTask: "Deploy a live production Docker stack on OCI Always Free ARM VM with automatic Let's Encrypt SSL.",
        mentalModelSnippet: "# Ingress Security Rules on OCI VCN:\n# Port 22 (SSH with key authentication)\n# Port 80 (HTTP redirect to HTTPS)\n# Port 443 (HTTPS Cloudflare SSL proxy)",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "Oracle Cloud Architecture Guide", url: "https://oracle.com/cloud", type: "doc", provider: "Oracle Devs", isFree: true },
        ],
      },
      {
        id: "k8s-orchestration",
        title: "Kubernetes & Pods",
        subtitle: "Clustering & Service Discovery",
        category: "Orchestration",
        level: "Advanced",
        x: 960,
        y: 270,
        dependencies: ["docker-containers"],
        estimatedHours: 35,
        matchedJobsCount: 21,
        skills: ["Kubernetes", "K3s / Minikube", "Deployments", "Ingress"],
        keyTopics: ["Control plane, etcd, and worker nodes", "Deployments, ReplicaSets & Pod scaling", "ClusterIP vs NodePort vs Ingress Services", "ConfigMaps, Secrets & Persistent Volume Claims"],
        description: "Understand the control plane, pods, replica sets, cluster IP services, ingress controllers, config maps, and persistent volume claims.",
        projectTask: "Deploy a microservice application on local K3s with rolling updates and zero-downtime restarts.",
        mentalModelSnippet: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-app\nspec:\n  replicas: 3\n  selector:\n    matchLabels:\n      app: web\n  template:\n    metadata:\n      labels:\n        app: web\n    spec:\n      containers:\n      - name: web\n        image: my-registry/web:1.0",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "Kubernetes The Hard Way", url: "https://github.com/kelseyhightower/kubernetes-the-hard-way", type: "course", provider: "Kelsey Hightower", isFree: true },
        ],
      },
      {
        id: "ci-cd-pipelines",
        title: "CI/CD & Infrastructure as Code",
        subtitle: "Automated Deployments",
        category: "Automation",
        level: "Advanced",
        x: 1260,
        y: 180,
        dependencies: ["oci-cloud-infra", "k8s-orchestration"],
        estimatedHours: 30,
        matchedJobsCount: 23,
        skills: ["GitHub Actions", "Terraform", "Zero-Downtime Deployment"],
        keyTopics: ["GitHub Actions workflows & runner matrices", "Declarative Terraform providers & state", "Blue-Green & Canary deployment strategies", "Automated rollbacks on healthcheck failure"],
        description: "Write declarative Terraform configurations, build automated CI/CD pipelines with rollback capabilities, and canary releases.",
        projectTask: "Build an automated pipeline that builds a Docker image on PR merge, pushes to registry, and deploys via SSH to VM.",
        mentalModelSnippet: "name: CI/CD Pipeline\non:\n  push:\n    branches: [main]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n    - uses: actions/checkout@v4\n    - run: docker build -t app:latest .\n    - run: ssh user@server 'docker compose up -d --pull'",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "Learn Terraform by HashiCorp", url: "https://developer.hashicorp.com/terraform/tutorials", type: "doc", provider: "HashiCorp", isFree: true },
        ],
      },
      {
        id: "devops-capstone",
        title: "Self-Healing Cloud Infrastructure",
        subtitle: "Production Reliability Capstone",
        category: "Capstone",
        level: "Capstone",
        x: 1560,
        y: 180,
        dependencies: ["ci-cd-pipelines"],
        estimatedHours: 40,
        matchedJobsCount: 25,
        skills: ["SRE Principles", "Prometheus & Grafana", "Automated Failover"],
        keyTopics: ["Prometheus metrics scraping & alertmanager", "Grafana dashboards for latency, error rate & saturation", "Self-healing container restarts & auto-scaling", "Disaster recovery & automated backup policies"],
        description: "Deploy a monitored, self-healing production environment with Prometheus metrics, Grafana dashboards, and automated failover.",
        projectTask: "Deliver a monitored high-availability cluster with automated alerts, rate limiting, and 99.9% uptime validation.",
        mentalModelSnippet: "# SRE Golden Signals:\n# 1. Latency (time taken to service requests)\n# 2. Traffic (demand placed on system)\n# 3. Errors (rate of requests failing)\n# 4. Saturation (how full service is)",
        matchedCourseId: "nana-devops-bootcamp",
        resources: [
          { title: "Google SRE Book", url: "https://sre.google/sre-book/table-of-contents", type: "doc", provider: "Google Engineering", isFree: true },
        ],
      },
    ],
  },
];
