export interface SalaryRecord {
  id: string;
  companyName: string;
  companySlug: string;
  tier: "BIG_TECH" | "UNICORN" | "PRODUCT" | "IT_SERVICES";
  role: string;
  roleTrack: "BACKEND" | "FRONTEND" | "FULLSTACK" | "AIML" | "DEVOPS_DATA" | "GENERAL";
  level: "FRESHER" | "SDE_1" | "SDE_2" | "STAFF";
  experienceYears: string;
  baseSalaryLpa: number;
  bonusLpa: number;
  stocksLpa: number;
  totalCtcLpa: number;
  estimatedMonthlyInHand: string;
  location: string;
  workMode: "Remote" | "Hybrid" | "On-site";
  interviewRounds: string;
  typicalTimelineDays: number;
  marketPercentile: "Top 5%" | "Top 15%" | "Median (50%)" | "Industry Standard";
  verifiedSubmissions?: number;
  status?: "APPROVED" | "PENDING_VERIFICATION" | "REJECTED";
  submittedAt?: string;
  submitterEmail?: string;
  sourceNote?: string;
}

export const COMPREHENSIVE_INDIAN_SALARIES: SalaryRecord[] = [
  // BIG TECH / FAANG
  {
    id: "sal-goog-l3",
    companyName: "Google India",
    companySlug: "google",
    tier: "BIG_TECH",
    role: "Software Engineer (L3)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 24,
    bonusLpa: 3.6,
    stocksLpa: 15,
    totalCtcLpa: 42.6,
    estimatedMonthlyInHand: "₹1.50L – ₹1.65L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "Online Assessment + 4 Technical Rounds + Googliness",
    typicalTimelineDays: 24,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-goog-l4",
    companyName: "Google India",
    companySlug: "google",
    tier: "BIG_TECH",
    role: "Software Engineer II (L4)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "2-4 Yrs",
    baseSalaryLpa: 36,
    bonusLpa: 5.4,
    stocksLpa: 24,
    totalCtcLpa: 65.4,
    estimatedMonthlyInHand: "₹2.20L – ₹2.40L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "Recruiter Phone Screen + 4 Coding + 1 System Design + Googliness",
    typicalTimelineDays: 28,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-msft-l59",
    companyName: "Microsoft IDC",
    companySlug: "microsoft",
    tier: "BIG_TECH",
    role: "Software Engineer (L59)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 3,
    stocksLpa: 9,
    totalCtcLpa: 30,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Hyderabad / Bangalore / Noida",
    workMode: "Hybrid",
    interviewRounds: "Online Test + 3 Technical Rounds + AA (As Appropriate)",
    typicalTimelineDays: 21,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-msft-l60",
    companyName: "Microsoft IDC",
    companySlug: "microsoft",
    tier: "BIG_TECH",
    role: "Software Engineer (L60)",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 23,
    bonusLpa: 3.5,
    stocksLpa: 12,
    totalCtcLpa: 38.5,
    estimatedMonthlyInHand: "₹1.45L – ₹1.58L / mo",
    location: "Hyderabad / Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Screening + 3 Coding Rounds + System Design + Managerial",
    typicalTimelineDays: 24,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-msft-l61",
    companyName: "Microsoft IDC",
    companySlug: "microsoft",
    tier: "BIG_TECH",
    role: "Software Engineer II (L61)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 32,
    bonusLpa: 5,
    stocksLpa: 18,
    totalCtcLpa: 55,
    estimatedMonthlyInHand: "₹1.95L – ₹2.15L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "3 System Design & DSA Rounds + Partner Director Interview",
    typicalTimelineDays: 25,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-amzn-sde1",
    companyName: "Amazon India",
    companySlug: "amazon",
    tier: "BIG_TECH",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "0-2 Yrs",
    baseSalaryLpa: 18.5,
    bonusLpa: 5,
    stocksLpa: 8.5,
    totalCtcLpa: 32,
    estimatedMonthlyInHand: "₹1.20L – ₹1.35L / mo",
    location: "Bangalore / Hyderabad / Chennai",
    workMode: "On-site",
    interviewRounds: "Online Assessment (2 DSA + Work Style) + 3 Virtual Onsite + Bar Raiser",
    typicalTimelineDays: 20,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-amzn-sde2",
    companyName: "Amazon India",
    companySlug: "amazon",
    tier: "BIG_TECH",
    role: "Software Development Engineer II",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 34,
    bonusLpa: 6,
    stocksLpa: 18,
    totalCtcLpa: 58,
    estimatedMonthlyInHand: "₹2.05L – ₹2.25L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "On-site",
    interviewRounds: "1 Screen + 2 High Level & Low Level Design + 1 DSA + 1 Bar Raiser (LP heavy)",
    typicalTimelineDays: 22,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-uber-l3",
    companyName: "Uber India",
    companySlug: "uber",
    tier: "BIG_TECH",
    role: "Software Engineer (L3)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 26,
    bonusLpa: 3.5,
    stocksLpa: 14,
    totalCtcLpa: 43.5,
    estimatedMonthlyInHand: "₹1.60L – ₹1.75L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "CodeSignal Screening + 3 Coding & Machine Coding + 1 Bar Raiser",
    typicalTimelineDays: 18,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-uber-l4",
    companyName: "Uber India",
    companySlug: "uber",
    tier: "BIG_TECH",
    role: "Senior Software Engineer (L4)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 40,
    bonusLpa: 5.5,
    stocksLpa: 25,
    totalCtcLpa: 70.5,
    estimatedMonthlyInHand: "₹2.45L – ₹2.70L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "1 System Architecture + 2 Advanced Coding + 1 Past Work Deep Dive + Cultural",
    typicalTimelineDays: 21,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-atlassian-p3",
    companyName: "Atlassian India",
    companySlug: "atlassian",
    tier: "BIG_TECH",
    role: "Software Engineer (P3)",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 28,
    bonusLpa: 3,
    stocksLpa: 15,
    totalCtcLpa: 46,
    estimatedMonthlyInHand: "₹1.70L – ₹1.85L / mo",
    location: "Remote (All India)",
    workMode: "Remote",
    interviewRounds: "Karat Screen + 2 Technical Craft + 1 System Design + 1 Values Interview",
    typicalTimelineDays: 19,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-atlassian-p4",
    companyName: "Atlassian India",
    companySlug: "atlassian",
    tier: "BIG_TECH",
    role: "Senior Software Engineer (P4)",
    roleTrack: "FULLSTACK",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 42,
    bonusLpa: 5,
    stocksLpa: 25,
    totalCtcLpa: 72,
    estimatedMonthlyInHand: "₹2.55L – ₹2.80L / mo",
    location: "Remote (All India)",
    workMode: "Remote",
    interviewRounds: "Architecture Design + Coding & Concurrency + Management & Values",
    typicalTimelineDays: 22,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-salesforce-mts",
    companyName: "Salesforce India",
    companySlug: "salesforce",
    tier: "BIG_TECH",
    role: "Member of Technical Staff (MTS)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 27,
    bonusLpa: 3.5,
    stocksLpa: 12,
    totalCtcLpa: 42.5,
    estimatedMonthlyInHand: "₹1.65L – ₹1.78L / mo",
    location: "Hyderabad / Bangalore",
    workMode: "Hybrid",
    interviewRounds: "HackerRank Test + 3 Technical Coding + 1 Managerial / Core Values",
    typicalTimelineDays: 23,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-cisco-gr4",
    companyName: "Cisco India",
    companySlug: "cisco",
    tier: "BIG_TECH",
    role: "Software Engineer (Grade 4)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 14.5,
    bonusLpa: 1.5,
    stocksLpa: 3,
    totalCtcLpa: 19,
    estimatedMonthlyInHand: "₹95K – ₹1.02L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Online Assessment + 2 Technical + 1 Managerial + HR",
    typicalTimelineDays: 16,
    
    marketPercentile: "Median (50%)",
  },
  {
    id: "sal-oracle-ic2",
    companyName: "Oracle India (OCI)",
    companySlug: "oracle",
    tier: "BIG_TECH",
    role: "Software Developer 2 (IC2)",
    roleTrack: "DEVOPS_DATA",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 19,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 25,
    estimatedMonthlyInHand: "₹1.20L – ₹1.30L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "3 DSA & Systems Coding + 1 Cloud Architecture Discussion",
    typicalTimelineDays: 20,
    
    marketPercentile: "Median (50%)",
  },

  // TOP INDIAN UNICORNS & HIGH-GROWTH TECH
  {
    id: "sal-razorpay-sde1",
    companyName: "Razorpay",
    companySlug: "razorpay",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 20,
    bonusLpa: 2,
    stocksLpa: 5,
    totalCtcLpa: 27,
    estimatedMonthlyInHand: "₹1.25L – ₹1.35L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding Round (2.5h) + Problem Solving (DSA) + Tech Arch + Culture",
    typicalTimelineDays: 14,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-razorpay-sde2",
    companyName: "Razorpay",
    companySlug: "razorpay",
    tier: "UNICORN",
    role: "Software Development Engineer II",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 32,
    bonusLpa: 4,
    stocksLpa: 10,
    totalCtcLpa: 46,
    estimatedMonthlyInHand: "₹1.95L – ₹2.10L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "High Level System Design + Low Level Design + Past Project Architecture + Fit",
    typicalTimelineDays: 16,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-cred-sde1",
    companyName: "CRED",
    companySlug: "cred",
    tier: "UNICORN",
    role: "Backend Engineer",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 25,
    bonusLpa: 2.5,
    stocksLpa: 7,
    totalCtcLpa: 34.5,
    estimatedMonthlyInHand: "₹1.55L – ₹1.68L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "Take Home / Machine Coding + 2 Deep Concurrency & Data Modeling + Founder Round",
    typicalTimelineDays: 12,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-cred-sde2",
    companyName: "CRED",
    companySlug: "cred",
    tier: "UNICORN",
    role: "Senior Product Engineer",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 38,
    bonusLpa: 4.5,
    stocksLpa: 16,
    totalCtcLpa: 58.5,
    estimatedMonthlyInHand: "₹2.30L – ₹2.55L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "Large Scale Distributed Systems + LLD Kafka & Redis + Leadership & Philosophy",
    typicalTimelineDays: 14,
    
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-zepto-sde1",
    companyName: "Zepto",
    companySlug: "zepto",
    tier: "UNICORN",
    role: "Backend Engineer (Go / Rust)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 22,
    bonusLpa: 3,
    stocksLpa: 6,
    totalCtcLpa: 31,
    estimatedMonthlyInHand: "₹1.35L – ₹1.48L / mo",
    location: "Bangalore / Mumbai",
    workMode: "On-site",
    interviewRounds: "Machine Coding in Go + High Concurrency DSA + System Architecture",
    typicalTimelineDays: 10,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-swiggy-sde1",
    companyName: "Swiggy",
    companySlug: "swiggy",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "FRONTEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 24,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Bangalore (Remote / Hybrid)",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding UI / State Management + Problem Solving + Hiring Manager",
    typicalTimelineDays: 15,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-swiggy-sde2",
    companyName: "Swiggy",
    companySlug: "swiggy",
    tier: "UNICORN",
    role: "Software Development Engineer II",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 29,
    bonusLpa: 3.5,
    stocksLpa: 9,
    totalCtcLpa: 41.5,
    estimatedMonthlyInHand: "₹1.80L – ₹1.95L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "HLD Microservices + LLD Machine Coding + Past Architecture Discussion",
    typicalTimelineDays: 18,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-zomato-sde1",
    companyName: "Zomato / Blinkit",
    companySlug: "zomato",
    tier: "UNICORN",
    role: "Software Development Engineer",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 19,
    bonusLpa: 2,
    stocksLpa: 5,
    totalCtcLpa: 26,
    estimatedMonthlyInHand: "₹1.20L – ₹1.30L / mo",
    location: "Gurgaon",
    workMode: "On-site",
    interviewRounds: "Live Coding & Algorithm + Machine Coding (React / Node) + Team Fit",
    typicalTimelineDays: 12,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-phonepe-ase",
    companyName: "PhonePe",
    companySlug: "phonepe",
    tier: "UNICORN",
    role: "Associate Software Engineer",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 16,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 22,
    estimatedMonthlyInHand: "₹1.05L – ₹1.15L / mo",
    location: "Bangalore / Pune",
    workMode: "On-site",
    interviewRounds: "Campus / Off-Campus Online Test + 2 DSA Rounds + 1 CS Fundamentals & Java",
    typicalTimelineDays: 17,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-phonepe-se",
    companyName: "PhonePe",
    companySlug: "phonepe",
    tier: "UNICORN",
    role: "Software Engineer",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 24,
    bonusLpa: 3.5,
    stocksLpa: 8,
    totalCtcLpa: 35.5,
    estimatedMonthlyInHand: "₹1.50L – ₹1.65L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "Machine Coding (Clean Architecture) + DSA + Low Level Design + Engineering Lead",
    typicalTimelineDays: 18,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-flipkart-sde1",
    companyName: "Flipkart",
    companySlug: "flipkart",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 19,
    bonusLpa: 2.5,
    stocksLpa: 5,
    totalCtcLpa: 26.5,
    estimatedMonthlyInHand: "₹1.20L – ₹1.32L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding Round (Design Patterns) + 2 Problem Solving DSA + Hiring Manager",
    typicalTimelineDays: 18,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-meesho-sde1",
    companyName: "Meesho",
    companySlug: "meesho",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 20,
    bonusLpa: 2,
    stocksLpa: 5,
    totalCtcLpa: 27,
    estimatedMonthlyInHand: "₹1.25L – ₹1.38L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding + Problem Solving + Architecture Discussion + Culture",
    typicalTimelineDays: 14,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-groww-sde1",
    companyName: "Groww",
    companySlug: "groww",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 24,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "Machine Coding (Spring Boot / Node) + DSA + CS Fundamentals + Culture Fit",
    typicalTimelineDays: 14,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-zerodha-be",
    companyName: "Zerodha",
    companySlug: "zerodha",
    tier: "PRODUCT",
    role: "Backend Engineer (Go / Python)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 24,
    bonusLpa: 4,
    stocksLpa: 0,
    totalCtcLpa: 28,
    estimatedMonthlyInHand: "₹1.50L – ₹1.65L / mo",
    location: "Bangalore / Remote",
    workMode: "Hybrid",
    interviewRounds: "Open Source Code Review + Practical Pair Programming + Systems & Networking + CTO",
    typicalTimelineDays: 12,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-postman-se",
    companyName: "Postman",
    companySlug: "postman",
    tier: "PRODUCT",
    role: "Software Engineer",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 22,
    bonusLpa: 2.5,
    stocksLpa: 7,
    totalCtcLpa: 31.5,
    estimatedMonthlyInHand: "₹1.35L – ₹1.45L / mo",
    location: "Bangalore / Remote",
    workMode: "Remote",
    interviewRounds: "Take-Home Assignment + Technical Deep Dive + DSA + Culture & Collaboration",
    typicalTimelineDays: 16,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-browserstack-se",
    companyName: "BrowserStack",
    companySlug: "browserstack",
    tier: "PRODUCT",
    role: "Software Engineer",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 24,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Mumbai / Remote",
    workMode: "Hybrid",
    interviewRounds: "Coding Challenge + 2 Technical Interviews (Systems & Concurrency) + HM",
    typicalTimelineDays: 15,
    
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-juspay-sde1",
    companyName: "Juspay",
    companySlug: "juspay",
    tier: "PRODUCT",
    role: "Software Development Engineer (Haskell / PureScript)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "0-2 Yrs",
    baseSalaryLpa: 17,
    bonusLpa: 2,
    stocksLpa: 3,
    totalCtcLpa: 22,
    estimatedMonthlyInHand: "₹1.10L – ₹1.20L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "Hacking Day / 2-Day Hackathon + Deep Functional Programming + Founder Chat",
    typicalTimelineDays: 10,
    
    marketPercentile: "Top 15%",
  },

  // IT SERVICES, GCCs & SERVICE SPECIALIST TRACKS
  {
    id: "sal-tcs-prime",
    companyName: "Tata Consultancy Services (TCS)",
    companySlug: "tcs",
    tier: "IT_SERVICES",
    role: "TCS Prime Developer",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 9,
    bonusLpa: 0.8,
    stocksLpa: 0,
    totalCtcLpa: 9.8,
    estimatedMonthlyInHand: "₹62K – ₹68K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "TCS NQT Advanced (Coding & DSA) + Technical Interview + MR/HR",
    typicalTimelineDays: 30,
    
    marketPercentile: "Median (50%)",
  },
  {
    id: "sal-tcs-digital",
    companyName: "Tata Consultancy Services (TCS)",
    companySlug: "tcs",
    tier: "IT_SERVICES",
    role: "TCS Digital Specialist",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 7,
    bonusLpa: 0.5,
    stocksLpa: 0,
    totalCtcLpa: 7.5,
    estimatedMonthlyInHand: "₹48K – ₹53K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "TCS NQT Coding Assessment + Technical Round + HR",
    typicalTimelineDays: 28,
    
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-tcs-ninja",
    companyName: "Tata Consultancy Services (TCS)",
    companySlug: "tcs",
    tier: "IT_SERVICES",
    role: "Assistant System Engineer (Ninja)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 3.36,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 3.36,
    estimatedMonthlyInHand: "₹24K – ₹26K / mo",
    location: "Pan-India",
    workMode: "On-site",
    interviewRounds: "TCS NQT Aptitude & Basic Coding + Combined TR/HR",
    typicalTimelineDays: 35,
    
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-infosys-sp",
    companyName: "Infosys",
    companySlug: "infosys",
    tier: "IT_SERVICES",
    role: "Specialist Programmer (Power Programmer)",
    roleTrack: "BACKEND",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 9.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 9.5,
    estimatedMonthlyInHand: "₹65K – ₹70K / mo",
    location: "Bangalore / Pune / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "HackWithInfy Contest (Rank 1-500) + Advanced DSA Technical Interview",
    typicalTimelineDays: 25,
    
    marketPercentile: "Median (50%)",
  },
  {
    id: "sal-infosys-dse",
    companyName: "Infosys",
    companySlug: "infosys",
    tier: "IT_SERVICES",
    role: "Digital Specialist Engineer (DSE)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 6.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 6.5,
    estimatedMonthlyInHand: "₹45K – ₹49K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "InfyTQ / HackWithInfy Qualifier + Technical Interview + HR",
    typicalTimelineDays: 30,
    
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-cognizant-elevate",
    companyName: "Cognizant",
    companySlug: "cognizant",
    tier: "IT_SERVICES",
    role: "Programmer Analyst Trainee (GenC Elevate)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 6.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 6.5,
    estimatedMonthlyInHand: "₹45K – ₹48K / mo",
    location: "Chennai / Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "Skill Assessment (Full Stack / Cloud) + Technical + HR",
    typicalTimelineDays: 28,
    
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-accenture-aaea",
    companyName: "Accenture India",
    companySlug: "accenture",
    tier: "IT_SERVICES",
    role: "Advanced Application Engineering Analyst",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 6.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 6.5,
    estimatedMonthlyInHand: "₹45K – ₹48K / mo",
    location: "Bangalore / Pune / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "Cognitive Assessment + Technical Assessment + Coding + HR Interview",
    typicalTimelineDays: 26,
    
    marketPercentile: "Industry Standard",
  },
  // GLOBAL TECH & GCCS IN INDIA
  {
    id: "sal-adobe-mts1",
    companyName: "Adobe India",
    companySlug: "adobe",
    tier: "BIG_TECH",
    role: "Member of Technical Staff 1 (MTS-1)",
    roleTrack: "FULLSTACK",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 16.5,
    bonusLpa: 2.5,
    stocksLpa: 10,
    totalCtcLpa: 29,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Bangalore / Noida",
    workMode: "Hybrid",
    interviewRounds: "Coding Assessment + 3 Technical Rounds (DSA/OS/OOP) + Director Round",
    typicalTimelineDays: 21,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-adobe-cs1",
    companyName: "Adobe India",
    companySlug: "adobe",
    tier: "BIG_TECH",
    role: "Computer Scientist 1 (CS-1)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 32,
    bonusLpa: 4.5,
    stocksLpa: 18,
    totalCtcLpa: 54.5,
    estimatedMonthlyInHand: "₹1.95L – ₹2.15L / mo",
    location: "Bangalore / Noida",
    workMode: "Hybrid",
    interviewRounds: "DSA Challenge + Low-Level Design + High-Level Distributed Architecture + HM",
    typicalTimelineDays: 24,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-intuit-se1",
    companyName: "Intuit India",
    companySlug: "intuit",
    tier: "BIG_TECH",
    role: "Software Engineer 1 (SWE-1)",
    roleTrack: "FULLSTACK",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 2.5,
    stocksLpa: 12,
    totalCtcLpa: 32.5,
    estimatedMonthlyInHand: "₹1.20L – ₹1.35L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Online Coding + Craft Demonstration (Take-Home Presentation) + 2 Technical + Value Assessment",
    typicalTimelineDays: 20,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-intuit-se2",
    companyName: "Intuit India",
    companySlug: "intuit",
    tier: "BIG_TECH",
    role: "Senior Software Engineer (SWE-2)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 34,
    bonusLpa: 5,
    stocksLpa: 22,
    totalCtcLpa: 61,
    estimatedMonthlyInHand: "₹2.10L – ₹2.30L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "System Design & Architecture + Deep Concurrency + Craft Defense + Manager",
    typicalTimelineDays: 22,
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-gs-analyst",
    companyName: "Goldman Sachs India",
    companySlug: "goldman-sachs",
    tier: "BIG_TECH",
    role: "Analyst (Software Engineering)",
    roleTrack: "BACKEND",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 20,
    bonusLpa: 4,
    stocksLpa: 0,
    totalCtcLpa: 24,
    estimatedMonthlyInHand: "₹1.35L – ₹1.45L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "HackerRank Math/Algo Test + 3 Technical Rounds (Data Structures, Math, OS) + VP Round",
    typicalTimelineDays: 25,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-gs-assoc",
    companyName: "Goldman Sachs India",
    companySlug: "goldman-sachs",
    tier: "BIG_TECH",
    role: "Associate (Senior Software Engineer)",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 35,
    bonusLpa: 10,
    stocksLpa: 0,
    totalCtcLpa: 45,
    estimatedMonthlyInHand: "₹2.20L – ₹2.40L / mo",
    location: "Bangalore / Hyderabad",
    workMode: "Hybrid",
    interviewRounds: "Low-Latency Java / Concurrency + Systems Architecture + Distributed Caching + Managing Director",
    typicalTimelineDays: 26,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-ms-analyst",
    companyName: "Morgan Stanley",
    companySlug: "morgan-stanley",
    tier: "BIG_TECH",
    role: "Technology Analyst",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 16,
    bonusLpa: 3,
    stocksLpa: 0,
    totalCtcLpa: 19,
    estimatedMonthlyInHand: "₹1.10L – ₹1.18L / mo",
    location: "Bangalore / Mumbai",
    workMode: "Hybrid",
    interviewRounds: "Online Assessment + 2 DSA/OOP Rounds + Systems & Database Internals + Executive Director",
    typicalTimelineDays: 22,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-walmart-se2",
    companyName: "Walmart Global Tech",
    companySlug: "walmart",
    tier: "BIG_TECH",
    role: "Software Engineer II",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 19,
    bonusLpa: 2.5,
    stocksLpa: 5.5,
    totalCtcLpa: 27,
    estimatedMonthlyInHand: "₹1.25L – ₹1.35L / mo",
    location: "Bangalore / Chennai",
    workMode: "Hybrid",
    interviewRounds: "Online Coding + 2 DSA Rounds + Spring Boot / Microservices Design + Hiring Manager",
    typicalTimelineDays: 18,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-walmart-sse",
    companyName: "Walmart Global Tech",
    companySlug: "walmart",
    tier: "BIG_TECH",
    role: "Senior Software Engineer",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 30,
    bonusLpa: 4.5,
    stocksLpa: 12,
    totalCtcLpa: 46.5,
    estimatedMonthlyInHand: "₹1.85L – ₹2.05L / mo",
    location: "Bangalore / Chennai",
    workMode: "Hybrid",
    interviewRounds: "High-Level Distributed Architecture + Low-Level Design + Concurrency + Staff Architect",
    typicalTimelineDays: 20,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-linkedin-se",
    companyName: "LinkedIn India",
    companySlug: "linkedin",
    tier: "BIG_TECH",
    role: "Software Engineer",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 24,
    bonusLpa: 3.5,
    stocksLpa: 16,
    totalCtcLpa: 43.5,
    estimatedMonthlyInHand: "₹1.55L – ₹1.70L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Host-Matching Coding + 2 Algorithms Rounds + Practical Debugging Loop + Cultural Alignment",
    typicalTimelineDays: 24,
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-linkedin-sse",
    companyName: "LinkedIn India",
    companySlug: "linkedin",
    tier: "BIG_TECH",
    role: "Senior Software Engineer",
    roleTrack: "BACKEND",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 38,
    bonusLpa: 5.5,
    stocksLpa: 26,
    totalCtcLpa: 69.5,
    estimatedMonthlyInHand: "₹2.40L – ₹2.65L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Distributed Systems Design + Data Modeling at Scale + Algorithmic Problem Solving + Engineering Director",
    typicalTimelineDays: 25,
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-nvidia-se",
    companyName: "NVIDIA India",
    companySlug: "nvidia",
    tier: "BIG_TECH",
    role: "System Software Engineer",
    roleTrack: "AIML",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 22,
    bonusLpa: 3,
    stocksLpa: 11,
    totalCtcLpa: 36,
    estimatedMonthlyInHand: "₹1.40L – ₹1.55L / mo",
    location: "Bangalore / Pune",
    workMode: "Hybrid",
    interviewRounds: "CUDA / C++ Internals + Systems Architecture + Concurrency & Memory Management + Technical Director",
    typicalTimelineDays: 25,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-nvidia-dl",
    companyName: "NVIDIA India",
    companySlug: "nvidia",
    tier: "BIG_TECH",
    role: "Senior Deep Learning Software Engineer",
    roleTrack: "AIML",
    level: "SDE_2",
    experienceYears: "3-5 Yrs",
    baseSalaryLpa: 36,
    bonusLpa: 5,
    stocksLpa: 20,
    totalCtcLpa: 61,
    estimatedMonthlyInHand: "₹2.15L – ₹2.35L / mo",
    location: "Bangalore / Pune",
    workMode: "Hybrid",
    interviewRounds: "Deep Learning Compiler / TensorRT + GPU Kernel Optimization + High-Performance Computing Loop + VP",
    typicalTimelineDays: 28,
    marketPercentile: "Top 5%",
  },
  {
    id: "sal-paypal-se1",
    companyName: "PayPal India",
    companySlug: "paypal",
    tier: "BIG_TECH",
    role: "Software Engineer 1",
    roleTrack: "BACKEND",
    level: "FRESHER",
    experienceYears: "0-2 Yrs",
    baseSalaryLpa: 17.5,
    bonusLpa: 2,
    stocksLpa: 5,
    totalCtcLpa: 24.5,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Bangalore / Chennai",
    workMode: "Hybrid",
    interviewRounds: "Online Assessment + 2 Problem Solving / DSA + Payments System LLD + Hiring Manager",
    typicalTimelineDays: 19,
    marketPercentile: "Top 15%",
  },
  // HIGH-GROWTH PRODUCT & UNICORNS
  {
    id: "sal-uc-sde1",
    companyName: "Urban Company",
    companySlug: "urban-company",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 20,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 26,
    estimatedMonthlyInHand: "₹1.25L – ₹1.38L / mo",
    location: "Gurgaon / Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding (Clean Architecture) + DSA Problem Solving + High Scale Microservices + Culture",
    typicalTimelineDays: 14,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-inmobi-sde1",
    companyName: "InMobi",
    companySlug: "inmobi",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 18,
    bonusLpa: 2,
    stocksLpa: 3,
    totalCtcLpa: 23,
    estimatedMonthlyInHand: "₹1.15L – ₹1.25L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Coding Challenge + 2 Technical DSA Rounds + Low-Latency Ad-Tech Architecture + VP",
    typicalTimelineDays: 16,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-coindcx-be",
    companyName: "CoinDCX",
    companySlug: "coindcx",
    tier: "PRODUCT",
    role: "Backend Engineer (Go / Distributed)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 22,
    bonusLpa: 2.5,
    stocksLpa: 4,
    totalCtcLpa: 28.5,
    estimatedMonthlyInHand: "₹1.35L – ₹1.48L / mo",
    location: "Bangalore / Remote",
    workMode: "Remote",
    interviewRounds: "Order Matching Machine Coding + High-Throughput Concurrency + Database Internals + Engineering Lead",
    typicalTimelineDays: 12,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-slice-se",
    companyName: "Slice",
    companySlug: "slice",
    tier: "UNICORN",
    role: "Software Engineer (FinTech Core)",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 20,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 26,
    estimatedMonthlyInHand: "₹1.25L – ₹1.35L / mo",
    location: "Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Machine Coding + Financial Ledger & Concurrency + DSA + Tech Director",
    typicalTimelineDays: 14,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-navi-sde1",
    companyName: "Navi Technologies",
    companySlug: "navi",
    tier: "PRODUCT",
    role: "Software Development Engineer I",
    roleTrack: "BACKEND",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 24,
    bonusLpa: 2,
    stocksLpa: 4,
    totalCtcLpa: 30,
    estimatedMonthlyInHand: "₹1.45L – ₹1.60L / mo",
    location: "Bangalore",
    workMode: "On-site",
    interviewRounds: "2 Fast-Paced DSA Coding Rounds + Low-Level Design (Machine Coding) + Founder / CTO Round",
    typicalTimelineDays: 10,
    marketPercentile: "Top 15%",
  },
  {
    id: "sal-lenskart-sde1",
    companyName: "Lenskart",
    companySlug: "lenskart",
    tier: "UNICORN",
    role: "Software Development Engineer I",
    roleTrack: "FULLSTACK",
    level: "SDE_1",
    experienceYears: "1-3 Yrs",
    baseSalaryLpa: 16,
    bonusLpa: 1.5,
    stocksLpa: 3,
    totalCtcLpa: 20.5,
    estimatedMonthlyInHand: "₹1.05L – ₹1.15L / mo",
    location: "Gurgaon / Bangalore",
    workMode: "Hybrid",
    interviewRounds: "Online Assessment + 2 Problem Solving Rounds + Fullstack App Architecture + HM",
    typicalTimelineDays: 16,
    marketPercentile: "Top 15%",
  },
  // IT SERVICES & CAMPUS RECRUITERS
  {
    id: "sal-wipro-elite",
    companyName: "Wipro",
    companySlug: "wipro",
    tier: "IT_SERVICES",
    role: "Project Engineer (Elite NLTH)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 3.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 3.5,
    estimatedMonthlyInHand: "₹25K – ₹27K / mo",
    location: "Pan-India",
    workMode: "On-site",
    interviewRounds: "Wipro Elite National Talent Hunt (Aptitude + Coding) + Technical / HR Interview",
    typicalTimelineDays: 32,
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-wipro-turbo",
    companyName: "Wipro",
    companySlug: "wipro",
    tier: "IT_SERVICES",
    role: "Project Engineer (Turbo / Velocity)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 6.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 6.5,
    estimatedMonthlyInHand: "₹45K – ₹48K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "Advanced Coding Round + Deep Technical Interview (Data Structures & Cloud) + HR",
    typicalTimelineDays: 28,
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-capgemini-exceller",
    companyName: "Capgemini",
    companySlug: "capgemini",
    tier: "IT_SERVICES",
    role: "Senior Analyst (Exceller Program)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 4.25,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 4.25,
    estimatedMonthlyInHand: "₹29K – ₹32K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "Pseudo-Code Test + English / Behavioral Test + Technical Interview + HR",
    typicalTimelineDays: 30,
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-capgemini-diff",
    companyName: "Capgemini",
    companySlug: "capgemini",
    tier: "IT_SERVICES",
    role: "Software Engineer (Differential / Adaptive Track)",
    roleTrack: "BACKEND",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 7.5,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 7.5,
    estimatedMonthlyInHand: "₹50K – ₹54K / mo",
    location: "Pan-India",
    workMode: "Hybrid",
    interviewRounds: "Advanced Coding Assessment + Fullstack/Architecture Technical Interview + HR",
    typicalTimelineDays: 25,
    marketPercentile: "Industry Standard",
  },
  {
    id: "sal-hcl-get",
    companyName: "HCLTech",
    companySlug: "hcltech",
    tier: "IT_SERVICES",
    role: "Graduate Engineer Trainee (GET)",
    roleTrack: "GENERAL",
    level: "FRESHER",
    experienceYears: "0-1 Yrs",
    baseSalaryLpa: 3.65,
    bonusLpa: 0,
    stocksLpa: 0,
    totalCtcLpa: 3.65,
    estimatedMonthlyInHand: "₹26K – ₹28K / mo",
    location: "Noida / Chennai / Bangalore",
    workMode: "On-site",
    interviewRounds: "Aptitude Assessment + Fundamental Coding + Technical Interview + HR Round",
    typicalTimelineDays: 30,
    marketPercentile: "Industry Standard",
  },
];
