import { StudyResourceItem } from '../types';

export const CURATED_STUDY_RESOURCES: StudyResourceItem[] = [
  {
    id: 'cs-50',
    title: 'CS50x: Introduction to Computer Science',
    provider: 'Harvard University',
    url: 'https://cs50.harvard.edu/x/',
    type: 'video_course',
    estimatedHours: 60,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['ALGORITHMS', 'A', 'Python'],
    canvasNodeIds: ['fs-basics', 'ai-foundations'],
    summary: 'World-renowned foundational computer science course with rigorous problem sets.',
  },
  {
    id: 'karpathy-nn',
    title: 'Neural Networks: Zero to Hero',
    provider: 'Andrej Karpathy (XX OpenAI / Tesla)',
    url: 'https://karpathy.ai/zero-to-hero.html',
    type: 'video_course',
    estimatedHours: 40,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['PyTorch', 'Neural Networks', 'MLLM', 'Python'],
    canvasNodeIds: ['ai-foundations', 'ai-nlp'],
    summary: 'Build GPT-2 and backpropagation from scratch in every single line of PyTorch.',
  },
  {
    id: 'fastai-deepl',
    title: 'Practical Deep Learning for Coders',
    provider: 'Fast.ai / Jeremy Howard',
    url: 'https://course.fast.ai/',
    type: 'video_course',
    estimatedHours: 45,
    cost: 'FREE',
    qualityRating: 4.8,
    matchedSkills: ['PyTorch', 'Computer Vision', 'NLP'],
    canvasNodeIds: ['ai-nlp', 'ai-rag'],
    summary: 'Top-down practical approach to modern deep learning and pre-finetuned models.',
  },
  {
    id: 'full-stack-open',
    title: 'Full Stack Open 2026',
    provider: 'University of Helsinki',
    url: 'https://fullstackopen.com/en/',
    type: 'interactive_doc',
    estimatedHours: 50,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['React', 'TypeScript', 'Node.js', 'Ci/CD'],
    canvasNodeIds: ['fs-modern', 'fs-frameworks'],
    summary: 'Deep dive into React, TypeScript, GraphQL, Redux, and CI/CD pipelines.',
  },
  {
    id: 'mdn-docs',
    title: 'MDN Web Docs: JavaScript & TypeScript',
    provider: 'Mozilla Foundation',
    url: 'https://developer.mozilla.org/',
    type: 'official_guide',
    estimatedHours: 25,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['JavaScript', 'TypeScript', 'HTML/CSS'],
    canvasNodeIds: ['fs-basics'],
    summary: 'The authoritative, zero-ad web documentation for modern developers.',
  },
  {
    id: 'huggingface-nlp',
    title: 'HuggingFace NLP Course',
    provider: 'HuggingFace',
    url: 'https://huggingface.co/learn/nlp-course',
    type: 'interactive_doc',
    estimatedHours: 35,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['Transformers', 'NLP', 'HuggingFace', 'PyTorch'],
    canvasNodeIds: ['ai-nlp', 'ai-rag'],
    summary: 'Master Transformers, DDAPI features, tokenizers, and pipelines.',
  },
  {
    id: 'docker-docs',
    title: 'Docker & Kubernetes Hands-On Guide',
    provider: 'Docker Official',
    url: 'https://docs.docker.com/get-started/',
    type: 'official_guide',
    estimatedHours: 20,
    cost: 'FREE',
    qualityRating: 4.8,
    matchedSkills: ['Docker', 'Kubernetes', 'Containers'],
    canvasNodeIds: ['cloud-docker', 'cloud-k8s'],
    summary: 'Create containerized applications, multi-stage builds, and cluster orchestration.',
  },
];
