import { StudyResourceItem } from '../types';

export const CURATED_STUDY_RESOURCES: StudyResourceItem[] = [
  {
    id: 'cs-50',
    title: 'CS50x: Introduction to Computer Science',
    provider: 'Harvard University',
    url: 'https://cs50.harvard.edu/x/',
    type: 'video_course',
    estimatedHours: 60,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['ALGORITHMS', 'A', 'Python'],
    canvasNodeIds: ['fs-basics', 'ai-foundations'],
    summary: 'World-renowned foundational computer science course with rigorous problem sets.',
  },
  {
    id: 'karpathy-nn',
    title: 'Neural Networks: Zero to Hero',
    provider: 'Andrej Karpathy (XX OpenAI / Tesla)',
    url: 'https://karpathy.ai/zero-to-hero.html',
    type: 'video_course',
    estimatedHours: 40,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['PyTorch', 'Neural Networks', 'MLLM', 'Python'],
    canvasNodeIds: ['ai-foundations', 'ai-nlp'],
    summary: 'Build GPT-2 and backpropagation from scratch in every single line of PyTorch.',
  },
  {
    id: 'fastai-deepl',
    title: 'Practical Deep Learning for Coders',
    provider: 'Fast.ai / Jeremy Howard',
    url: 'https://course.fast.ai/',
    type: 'video_course',
    estimatedHours: 45,
    cost: 'FREE',
    qualityRating: 4.8,
    matchedSkills: ['PyTorch', 'Computer Vision', 'NLP'],
    canvasNodeIds: ['ai-nlp', 'ai-rag'],
    summary: 'Top-down practical approach to modern deep learning and pre-finetuned models.',
  },
  {
    id: 'full-stack-open',
    title: 'Full Stack Open 2026',
    provider: 'University of Helsinki',
    url: 'https://fullstackopen.com/en/',
    type: 'interactive_doc',
    estimatedHours: 50,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['React', 'TypeScript', 'Node.js', 'Ci/CD'],
    canvasNodeIds: ['fs-modern', 'fs-frameworks'],
    summary: 'Deep dive into React, TypeScript, GraphQL, Redux, and CI/CD pipelines.',
  },
  {
    id: 'mdn-docs',
    title: 'MDN Web Docs: JavaScript & TypeScript',
    provider: 'Mozilla Foundation',
    url: 'https://developer.mozilla.org/',
    type: 'official_guide',
    estimatedHours: 25,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['JavaScript', 'TypeScript', 'HTML/CSS'],
    canvasNodeIds: ['fs-basics'],
    summary: 'The authoritative, zero-ad web documentation for modern developers.',
  },
  {
    id: 'huggingface-nlp',
    title: 'HuggingFace NLP Course',
    provider: 'HuggingFace',
    url: 'https://huggingface.co/learn/nlp-course',
    type: 'interactive_doc',
    estimatedHours: 35,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['Transformers', 'NLP', 'HuggingFace', 'PyTorch'],
    canvasNodeIds: ['ai-nlp', 'ai-rag'],
    summary: 'Master Transformers, DDAPI features, tokenizers, and pipelines.',
  },
  {
    id: 'docker-docs',
    title: 'Docker & Kubernetes Hands-On Guide',
    provider: 'Docker Official',
    url: 'https://docs.docker.com/get-started/',
    type: 'official_guide',
    estimatedHours: 20,
    cost: 'FREE',
    qualityRating: 4.8,
    matchedSkills: ['Docker', 'Kubernetes', 'Containers'],
    canvasNodeIds: ['cloud-docker', 'cloud-k8s'],
    summary: 'Create containerized applications, multi-stage builds, and cluster orchestration.',
  },
  {
    id: 'striver-dsa',
    title: "Striver's A2Z DSA Sheet",
    provider: 'take U forward',
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    type: 'video_course',
    estimatedHours: 100,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['Algorithms', 'Data Structures', 'C++', 'Java', 'Dynamic Programming'],
    canvasNodeIds: ['fs-basics', 'ai-foundations'],
    summary: 'The ultimate 450+ question DSA roadmap covering all coding interview patterns from scratch to advanced.',
  },
  {
    id: 'neetcode-150',
    title: 'NeetCode 150 Coding Interview Roadmap',
    provider: 'NeetCode',
    url: 'https://neetcode.io/practice',
    type: 'interactive_doc',
    estimatedHours: 50,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['Algorithms', 'Python', 'LeetCode', 'Pattern Recognition'],
    canvasNodeIds: ['fs-basics'],
    summary: 'Curated 150 essential problems covering all 18 core interview patterns with video solutions.',
  },
  {
    id: 'hussein-backend',
    title: 'Backend Engineering & Distributed Protocols',
    provider: 'Hussein Nasser',
    url: 'https://www.youtube.com/@hnasr',
    type: 'video_course',
    estimatedHours: 35,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['PostgreSQL', 'HTTP/3', 'gRPC', 'Proxies', 'Distributed Systems'],
    canvasNodeIds: ['fs-frameworks', 'cloud-docker'],
    summary: 'Master database storage engines, B-trees, connection pooling, and low-level network protocols.',
  },
  {
    id: 'gaurav-sen-hld',
    title: 'High-Level System Design (HLD)',
    provider: 'Gaurav Sen',
    url: 'https://www.youtube.com/@gkcs',
    type: 'video_course',
    estimatedHours: 25,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['System Design', 'Consistent Hashing', 'Distributed Caching', 'Microservices'],
    canvasNodeIds: ['fs-frameworks', 'cloud-k8s'],
    summary: 'Visual architecture breakdowns of WhatsApp, Netflix, and Tinder with sharding and consensus models.',
  },
  {
    id: 'nana-devops',
    title: 'Docker & Kubernetes Cloud-Native Bootcamp',
    provider: 'TechWorld with Nana',
    url: 'https://www.youtube.com/@TechWorldwithNana',
    type: 'video_course',
    estimatedHours: 30,
    cost: 'FREE',
    qualityRating: 4.9,
    matchedSkills: ['Docker', 'Kubernetes', 'Helm', 'DevOps', 'CI/CD'],
    canvasNodeIds: ['cloud-docker', 'cloud-k8s'],
    summary: 'Industry-standard containerization, Kubernetes manifest engineering, and GitOps orchestration.',
  },
  {
    id: 'mit-algo',
    title: 'MIT 6.006: Introduction to Algorithms',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    type: 'video_course',
    estimatedHours: 60,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['Algorithms', 'Complexity Analysis', 'Dynamic Programming', 'Graph Algorithms'],
    canvasNodeIds: ['fs-basics', 'ai-foundations'],
    summary: 'World-renowned MIT undergraduate curriculum taught by Erik Demaine and Srini Devadas.',
  },
  {
    id: 'stanford-cs229',
    title: 'Stanford CS229: Machine Learning',
    provider: 'Stanford University / Andrew Ng',
    url: 'https://cs229.stanford.edu/',
    type: 'video_course',
    estimatedHours: 55,
    cost: 'FREE',
    qualityRating: 5.0,
    matchedSkills: ['Machine Learning', 'Linear Algebra', 'Gradient Descent', 'SVMs', 'Neural Networks'],
    canvasNodeIds: ['ai-foundations', 'ai-nlp'],
    summary: 'The bedrock machine learning course from Andrew Ng covering rigorous statistical learning theory.',
  },
];
