// scripts/potd-catalog.mjs
// Rotating 30+ Industrial Coding Problems of the Day (POTD) covering all RoleNest domains

export const POTD_CATALOG = [
  {
    id: 1,
    domain: "Full-Stack & Next.js 15",
    title: "Optimistic UI State & Server Action Rollback",
    difficulty: "Medium",
    tags: ["React 19", "Next.js App Router", "Server Actions"],
    description:
      "When a candidate upvotes a project in RoleNest DevShelf, the UI updates instantly using React `useOptimistic`. However, if the Server Action fails due to a network glitch, how do you gracefully rollback the UI and display an error toast without triggering a full page re-render?",
    codeSnippet: `// Next.js 15 Server Action snippet
export async function toggleUpvote(projectId: string) {
  'use server';
  // Simulate occasional 500 error
  if (Math.random() < 0.2) throw new Error("Database timeout");
  return await db.upvote(projectId);
}`,
    challengeTask:
      "Implement the client component using `useActionState` and `useOptimistic` to demonstrate seamless rollback when the server action throws.",
    hint: "Remember that useOptimistic takes an updateFn that derives the temporary state from the confirmed state and optimistic input.",
  },
  {
    id: 2,
    domain: "Artificial Intelligence & ML",
    title: "Vector Cosine Similarity & Dense Embedding Ranker",
    difficulty: "Hard",
    tags: ["PyTorch", "Vector Search", "Linear Algebra"],
    description:
      "Given two high-dimensional embedding matrices `A` (shape: [N, D]) and `B` (shape: [M, D]) generated by a transformer model, write a vectorized PyTorch function to compute the pairwise cosine similarity matrix without using standard nested for-loops.",
    codeSnippet: `import torch

def pairwise_cosine_similarity(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor:
    # A: [N, D], B: [M, D]
    # Return: [N, M] cosine similarities
    pass`,
    challengeTask:
      "Normalize both matrices along dimension 1 with `F.normalize(p=2, dim=1)` and use matrix multiplication `A @ B.T` for GPU acceleration.",
    hint: "Cosine similarity between unit vectors is simply their dot product!",
  },
  {
    id: 3,
    domain: "Cybersecurity & InfoSec",
    title: "Timing Attack Vulnerability in Constant-Time Secret Verification",
    difficulty: "Medium",
    tags: ["OWASP", "Cryptography", "Node.js Crypto"],
    description:
      "A developer validates an internal webhook HMAC signature using `receivedSig === calculatedSig`. Why is this vulnerable to a timing attack, and how do you fix it using Node.js crypto primitives?",
    codeSnippet: `// Flawed verification:
function verifyWebhook(receivedSig, calculatedSig) {
  return receivedSig === calculatedSig; // VULNERABLE!
}`,
    challengeTask:
      "Replace string equality with `crypto.timingSafeEqual(Buffer.from(...), Buffer.from(...))` and explain why variable-time string comparison leaks secret length and byte values.",
    hint: "String `===` terminates on the first mismatched byte, taking less CPU time for incorrect prefixes.",
  },
  {
    id: 4,
    domain: "Databases & PostgreSQL",
    title: "PostgreSQL N+1 Query Elimination & Window Functions",
    difficulty: "Medium",
    tags: ["PostgreSQL", "SQL Performance", "Indexing"],
    description:
      "You have an `enrollments` table with 500,000 records. Write a single SQL query that finds the top 3 highest-scoring interns per track without performing multiple queries per track.",
    codeSnippet: `SELECT student_name, track_id, audit_score
FROM (
  SELECT student_name, track_id, audit_score,
         DENSE_RANK() OVER (PARTITION BY track_id ORDER BY audit_score DESC) as rank
  FROM bootcamp_enrollments
) ranked
WHERE rank <= 3;`,
    challengeTask:
      "Explain the performance difference between `ROW_NUMBER()`, `RANK()`, and `DENSE_RANK()`, and design the composite index required for index-only scanning.",
    hint: "An index on `(track_id, audit_score DESC, student_name)` satisfies the query without visiting heap pages.",
  },
  {
    id: 5,
    domain: "DevOps & Cloud SRE",
    title: "Docker Multi-Stage Build & Distroless Image Optimization",
    difficulty: "Medium",
    tags: ["Docker", "Kubernetes", "Container Security"],
    description:
      "A developer's Next.js container image is 1.4 GB because it includes `node_modules`, build caches, and devDependencies. Write an optimized 3-stage Dockerfile that drops the final image size below 150 MB using Next.js standalone output and Google Distroless.",
    codeSnippet: `FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
# Build standalone output...`,
    challengeTask:
      "Configure `output: 'standalone'` in `next.config.js` and build a minimal runner container copying only `.next/standalone` and `.next/static`.",
    hint: "Distroless containers contain only your application and its runtime dependencies, eliminating bash and package managers for zero attack surface.",
  },
  {
    id: 6,
    domain: "Git Plumbing & Systems",
    title: "Git DAG Internals: Blob, Tree, and Commit Object Traversal",
    difficulty: "Hard",
    tags: ["Git Internals", "SHA-1 / SHA-256", "Content Addressable DB"],
    description:
      "Given the 40-character SHA hash of a commit, describe step-by-step how Git reconstructs the working directory from `.git/objects` by traversing commit, tree, and blob objects.",
    codeSnippet: `git cat-file -p HEAD
# tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904
# parent a1b2c3...
# author ...`,
    challengeTask:
      "Explain how a commit points to a root tree object, subtrees represent directories, and blobs store raw file bytes without file names.",
    hint: "File names and permissions are stored inside tree entries, not in the blob objects themselves!",
  },
  {
    id: 7,
    domain: "Distributed Systems & WebSockets",
    title: "Distributed WebSocket Session Broadcast with Redis Pub/Sub",
    difficulty: "Hard",
    tags: ["WebSockets", "Redis", "Distributed Systems"],
    description:
      "When running multiple Node.js instances behind an Nginx load balancer, candidate A is connected to Instance 1 while candidate B is on Instance 2. How do you implement Redis Pub/Sub so that a real-time standup notification posted on Instance 1 reaches candidate B on Instance 2?",
    codeSnippet: `// Instance 1 publishes
redisPublisher.publish('standup-events', JSON.stringify({ student: 'Alex', day: 14 }));

// Instance 2 subscribes
redisSubscriber.subscribe('standup-events', (message) => {
  localWSServer.broadcast(message);
});`,
    challengeTask:
      "Diagram the publish-subscribe flow and explain how Redis Adapter prevents message looping and handles reconnection backoff.",
    hint: "Ensure your subscriber connection is dedicated exclusively to listening, as Redis subscriber sockets cannot issue standard key commands.",
  },
  {
    id: 8,
    domain: "Web3 & Blockchain",
    title: "EVM Smart Contract Reentrancy Vulnerability & Checks-Effects-Interactions",
    difficulty: "Hard",
    tags: ["Solidity", "EVM", "Smart Contract Security"],
    description:
      "In a Solidity withdrawal function, an external call `msg.sender.call{value: amount}(\"\")` is made before updating `balances[msg.sender] = 0`. Explain how an attacker exploits this with a fallback function to drain the contract, and refactor it following the CEI pattern.",
    codeSnippet: `// VULNERABLE:
function withdraw() public {
    uint amount = balances[msg.sender];
    (bool s, ) = msg.sender.call{value: amount}("");
    require(s);
    balances[msg.sender] = 0; // TOO LATE!
}`,
    challengeTask:
      "Rewrite the function with Checks-Effects-Interactions and use OpenZeppelin ReentrancyGuard mutex locks.",
    hint: "Always deduct the user's balance in state BEFORE transferring any Ether to an external contract.",
  },
];

/**
 * Returns today's Problem of the Day based on the day of the year.
 */
export function getDailyPOTD() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now - start;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);

  const index = dayOfYear % POTD_CATALOG.length;
  return {
    ...POTD_CATALOG[index],
    dayOfYear,
    dateString: now.toLocaleDateString("en-IN", {
      timeZone: "Asia/Kolkata",
      weekday: "long",
      year: "numeric",
      month: "short",
      day: "numeric",
    }),
  };
}
