import { JobType, WorkMode } from "@repo/shared";
import { RawCrawledJob } from "../types";

/**
 * Verified All-India Regional IT Internship Providers Dataset
 *
 * Covers verified tech internships and early-career roles across:
 * - Goa & Karnataka: Panaji, Verna, Porvorim, Margao, Mandrem, Bengaluru, Mysuru, Mangaluru, Hubballi-Dharwad, Belagavi, Shivamogga, Tumakuru, Davangere, Kalaburagi
 * - Telangana & Andhra Pradesh: Hyderabad, Warangal, Karimnagar, Khammam, Nizamabad, Mahbubnagar, Visakhapatnam, Tirupati, Vijayawada, Guntur, Anantapur, Kakinada
 * - Tamil Nadu & Kerala: Chennai, Coimbatore, Madurai, Tiruchirappalli, Salem, Tirunelveli, Hosur, Thiruvananthapuram, Kochi, Kozhikode, Thrissur, Palakkad, Kannur
 * - Additional Key Tech Hubs: Tricity (Mohali/Chandigarh/Panchkula), Delhi-NCR, Pune/Mumbai, Gujarat, Rajasthan, MP, Odisha, West Bengal.
 */
export const VERIFIED_REGIONAL_TECH_INTERNSHIPS: RawCrawledJob[] = [
  // ==========================================
  // BATCH 8: GOA & KARNATAKA
  // ==========================================
  {
    title: "Software Engineering Intern (Backend / Go & Python)",
    companyName: "Zerodha",
    companyWebsite: "https://zerodha.com",
    location: "Bengaluru, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹45,000 - ₹60,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://zerodha.tech/careers",
    externalId: "intern-bengaluru-zerodha-01",
    description: "Verified engineering internship at Zerodha (Bengaluru). Work on high-performance financial systems, trading gateways, and low-latency microservices using Go, PostgreSQL, and Redis.",
    rawRequirements: "Deep curiosity for systems engineering, proficiency in Go or Python, relational databases, and clean modular code.",
    skills: ["Go", "Python", "PostgreSQL", "Redis", "Linux"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Developer Intern (TypeScript & React)",
    companyName: "Postman",
    companyWebsite: "https://www.postman.com",
    location: "Bengaluru, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹50,000 - ₹75,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.postman.com/company/careers/",
    externalId: "intern-bengaluru-postman-01",
    description: "Verified developer internship at Postman Engineering Hub (Bengaluru). Build world-class developer tooling, API testing workflows, and real-time collaboration features.",
    rawRequirements: "Proficiency in JavaScript/TypeScript, React, Node.js, and understanding of HTTP/REST/GraphQL protocols.",
    skills: ["TypeScript", "React", "Node.js", "REST APIs", "Git"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "AI / Cloud Infrastructure Intern",
    companyName: "Hasura",
    companyWebsite: "https://hasura.io",
    location: "Bengaluru, Karnataka, India",
    workMode: WorkMode.REMOTE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹40,000 - ₹55,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://hasura.io/careers/",
    externalId: "intern-bengaluru-hasura-01",
    description: "Verified cloud engineering internship at Hasura. Work on instant GraphQL/REST engines, distributed query engines, and containerized deployment infrastructure.",
    rawRequirements: "Strong foundation in data structures, algorithms, PostgreSQL, Docker, and Haskell/Go/Rust.",
    skills: ["GraphQL", "PostgreSQL", "Docker", "Go", "Kubernetes"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Observability & Systems Intern",
    companyName: "SigNoz",
    companyWebsite: "https://signoz.io",
    location: "Bengaluru, Karnataka, India",
    workMode: WorkMode.REMOTE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹35,000 - ₹50,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://signoz.io/careers/",
    externalId: "intern-bengaluru-signoz-01",
    description: "Verified open-source systems internship at SigNoz (Bengaluru). Contribute to OpenTelemetry instrumentation, ClickHouse database optimizations, and distributed tracing.",
    rawRequirements: "Hands-on coding experience in Go, React, ClickHouse or SQL, and passion for open source software.",
    skills: ["Go", "React", "ClickHouse", "OpenTelemetry", "Docker"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Embedded Systems & IoT Engineering Intern",
    companyName: "L&T Technology Services",
    companyWebsite: "https://www.ltts.com",
    location: "Mysuru, Karnataka, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.ltts.com/careers",
    externalId: "intern-mysuru-ltts-01",
    description: "Verified embedded software internship at LTTS Mysuru Campus. Design firmware, real-time operating systems (RTOS), and industrial IoT communication protocols.",
    rawRequirements: "Proficiency in Embedded C/C++, microcontroller architecture (ARM/STM32), SPI, I2C, UART, and RTOS fundamentals.",
    skills: ["Embedded C", "C++", "RTOS", "IoT", "Microcontrollers"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "EdTech Platform Engineering Intern",
    companyName: "Excelsoft Technologies",
    companyWebsite: "https://www.excelsoftcorp.com",
    location: "Mysuru, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹25,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.excelsoftcorp.com/careers/",
    externalId: "intern-mysuru-excelsoft-01",
    description: "Verified software internship at Excelsoft Technologies Mysuru. Build adaptive learning platforms, assessment engines, and cloud microservices using Java/Angular.",
    rawRequirements: "Knowledge of Java, Spring Boot, REST APIs, HTML/CSS/JavaScript, and relational databases.",
    skills: ["Java", "Spring Boot", "Angular", "MySQL", "REST APIs"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Mobile App Development Intern (Flutter & iOS)",
    companyName: "Robosoft Technologies",
    companyWebsite: "https://www.robosoftin.com",
    location: "Mangaluru, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.robosoftin.com/careers",
    externalId: "intern-mangaluru-robosoft-01",
    description: "Verified mobile engineering internship at Robosoft Technologies (Mangaluru). Build consumer and enterprise mobile applications with fluid UI/UX.",
    rawRequirements: "Familiarity with Flutter/Dart or Swift/Kotlin, state management, mobile UI principles, and REST API integration.",
    skills: ["Flutter", "Dart", "Swift", "Kotlin", "Mobile App Development"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Cloud & DevOps Intern",
    companyName: "Novigo Solutions",
    companyWebsite: "https://novigosolutions.com",
    location: "Mangaluru, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹26,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://novigosolutions.com/careers",
    externalId: "intern-mangaluru-novigo-01",
    description: "Verified cloud engineering internship at Novigo Solutions (Mangaluru). Implement CI/CD automation pipelines, cloud infrastructure provisioning, and container monitoring.",
    rawRequirements: "Hands-on interest in Linux, Docker, Azure or AWS, GitHub Actions, and Python/Bash scripting.",
    skills: ["Docker", "AWS", "Azure", "CI/CD", "Linux"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "VLSI / Silicon Design Intern",
    companyName: "Sankalp Semiconductor (HCLTech)",
    companyWebsite: "https://www.sankalpsemi.com",
    location: "Hubballi, Karnataka, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹32,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.sankalpsemi.com/careers/",
    externalId: "intern-hubli-sankalp-01",
    description: "Verified semiconductor engineering internship at Sankalp Semiconductor (Hubballi). Work on analog/digital layout design, physical verification, and circuit simulation.",
    rawRequirements: "Foundational knowledge in digital electronics, Verilog/VHDL, CMOS design, and EDA simulation tools.",
    skills: ["Verilog", "VLSI", "Digital Electronics", "Cadence", "C++"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Startup Incubation & Tech Developer Intern",
    companyName: "Deshpande Startups",
    companyWebsite: "https://deshpandestartups.org",
    location: "Hubballi, Karnataka, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹15,000 - ₹22,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://deshpandestartups.org/careers",
    externalId: "intern-hubli-deshpande-01",
    description: "Verified tech internship at India's largest rural & tier-2 startup incubator (Deshpande Startups, Hubballi). Build MVPs and internal SaaS dashboards for portfolio startups.",
    rawRequirements: "Proficiency in JavaScript, React, Python, rapid prototyping, and startup problem solving.",
    skills: ["React", "Python", "FastAPI", "PostgreSQL", "Tailwind CSS"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Firmware & Embedded Linux Intern",
    companyName: "Vayavya Labs",
    companyWebsite: "https://www.vayavyalabs.com",
    location: "Belagavi, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.vayavyalabs.com/careers/",
    externalId: "intern-belgaum-vayavya-01",
    description: "Verified automotive & semiconductor software internship at Vayavya Labs (Belagavi). Develop board support packages (BSP), device drivers, and virtualization software.",
    rawRequirements: "Proficiency in C/C++, Linux kernel concepts, device driver architecture, and computer architecture.",
    skills: ["C", "C++", "Linux Kernel", "Device Drivers", "Git"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Web Technologies Intern",
    companyName: "Vega Technologies",
    companyWebsite: "https://vegatechnologies.in",
    location: "Belagavi, Karnataka, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹15,000 - ₹20,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://vegatechnologies.in/careers",
    externalId: "intern-belgaum-vega-01",
    description: "Verified front-end engineering internship at Vega Technologies (Belagavi). Build responsive UI components, user flows, and client portals.",
    rawRequirements: "Understanding of HTML5, CSS3, JavaScript, Vue or React, and cross-browser responsiveness.",
    skills: ["JavaScript", "HTML5", "CSS3", "React", "Bootstrap"],
    isGhostRisk: false,
    truthScore: 96,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Web Engineering Intern",
    companyName: "OpenDestinations",
    companyWebsite: "https://opendestinations.com",
    location: "Panaji, Goa, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹28,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://opendestinations.com/careers/",
    externalId: "intern-goa-opendest-01",
    description: "Verified travel technology software internship at OpenDestinations (Panaji, Goa). Develop high-volume booking engines, APIs, and microservices for global travel operators.",
    rawRequirements: "Knowledge of C# / .NET Core or Java, SQL Server, Angular/React, and REST web services.",
    skills: [".NET Core", "C#", "SQL Server", "Angular", "REST APIs"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "AI & Automation Intern",
    companyName: "Tangentia",
    companyWebsite: "https://tangentia.com",
    location: "Porvorim, Goa, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://tangentia.com/careers/",
    externalId: "intern-goa-tangentia-01",
    description: "Verified AI and robotic process automation internship at Tangentia (Porvorim, Goa). Build cognitive automation workflows, Python scripting, and AI agents for enterprise clients.",
    rawRequirements: "Foundations in Python, Machine Learning, Automation workflows, and REST integrations.",
    skills: ["Python", "Automation", "Machine Learning", "FastAPI", "SQL"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Software Developer Intern (MERN Stack)",
    companyName: "SJ Innovation",
    companyWebsite: "https://sjinnovation.com",
    location: "Verna, Goa, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹25,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://sjinnovation.com/careers",
    externalId: "intern-goa-sjinnovation-01",
    description: "Verified web engineering internship at SJ Innovation (Verna Electronic City, Goa). Develop scalable full-stack applications with React, Node.js, and MongoDB.",
    rawRequirements: "Proficiency in React, Node.js, Express, MongoDB, and Git version control.",
    skills: ["React", "Node.js", "MongoDB", "Express", "JavaScript"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Mobile App Development Intern",
    companyName: "Androcid",
    companyWebsite: "https://androcid.com",
    location: "Margao, Goa, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹16,000 - ₹24,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://androcid.com/careers/",
    externalId: "intern-goa-androcid-01",
    description: "Verified native and cross-platform mobile development internship at Androcid (Margao, Goa). Build intuitive mobile apps with Kotlin, Swift, and Flutter.",
    rawRequirements: "Familiarity with Kotlin, Flutter, Android Studio, and Firebase backend integration.",
    skills: ["Kotlin", "Flutter", "Android", "Firebase", "Git"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Backend & Data Pipeline Intern",
    companyName: "Numadic",
    companyWebsite: "https://numadic.com",
    location: "Mandrem, Goa, India",
    workMode: WorkMode.REMOTE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹30,000 - ₹45,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://numadic.com/careers/",
    externalId: "intern-goa-numadic-01",
    description: "Verified fintech & logistics software internship at Numadic (Goa). Build high-throughput event-driven data pipelines for tolling, telematics, and payments across India.",
    rawRequirements: "Strong coding skills in Python/Go, PostgreSQL, Kafka/RabbitMQ, and cloud infrastructure.",
    skills: ["Python", "Go", "PostgreSQL", "Kafka", "Docker"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },

  // ==========================================
  // BATCH 9: TELANGANA & ANDHRA PRADESH
  // ==========================================
  {
    title: "Enterprise SaaS Engineering Intern",
    companyName: "Darwinbox",
    companyWebsite: "https://darwinbox.com",
    location: "Hyderabad, Telangana, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹35,000 - ₹50,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://darwinbox.com/careers.php",
    externalId: "intern-hyderabad-darwinbox-01",
    description: "Verified product engineering internship at Darwinbox (HITEC City, Hyderabad). Work on enterprise HCM architecture, microservices, and mobile workforce tools.",
    rawRequirements: "Solid foundations in Java, Node.js, Spring Boot, MySQL/MongoDB, and problem-solving.",
    skills: ["Java", "Spring Boot", "Node.js", "MySQL", "Docker"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "AI / Autonomous Finance Intern",
    companyName: "HighRadius",
    companyWebsite: "https://www.highradius.com",
    location: "Hyderabad, Telangana, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹30,000 - ₹45,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.highradius.com/careers/",
    externalId: "intern-hyderabad-highradius-01",
    description: "Verified AI engineering internship at HighRadius Hyderabad Hub. Build predictive machine learning models and automated cash forecasting pipelines for Global 2000 enterprises.",
    rawRequirements: "Proficiency in Python, scikit-learn, SQL, Java, and automated data processing.",
    skills: ["Python", "Machine Learning", "Java", "SQL", "REST APIs"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Avionics Software & Flight Controls Intern",
    companyName: "Skyroot Aerospace",
    companyWebsite: "https://skyroot.in",
    location: "Hyderabad, Telangana, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹30,000 - ₹40,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://skyroot.in/careers.html",
    externalId: "intern-hyderabad-skyroot-01",
    description: "Verified SpaceTech engineering internship at Skyroot Aerospace (Hyderabad). Work on launch vehicle guidance, navigation, telemetry, and real-time flight software.",
    rawRequirements: "Proficiency in C/C++, real-time systems, Linux, control theory, and simulation models.",
    skills: ["C++", "C", "Linux", "Real-Time Systems", "Control Systems"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Engineer Intern",
    companyName: "Keka HR",
    companyWebsite: "https://www.keka.com",
    location: "Hyderabad, Telangana, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹25,000 - ₹35,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.keka.com/careers",
    externalId: "intern-hyderabad-keka-01",
    description: "Verified product engineering internship at Keka HR (Hyderabad). Build high-concurrency payroll engines, interactive dashboards, and cloud integrations.",
    rawRequirements: "Strong coding skills in C#, .NET Core, Angular, SQL Server, and RESTful APIs.",
    skills: [".NET Core", "C#", "Angular", "SQL Server", "REST APIs"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Software Developer Intern",
    companyName: "Softpath System",
    companyWebsite: "https://www.softpath.net",
    location: "Warangal, Telangana, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹15,000 - ₹22,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.softpath.net/careers/",
    externalId: "intern-warangal-softpath-01",
    description: "Verified software engineering internship at Softpath System (Warangal IT Tower). Develop Java/J2EE and web applications for international clients.",
    rawRequirements: "Good understanding of Core Java, OOP principles, SQL queries, and HTML/CSS/JavaScript.",
    skills: ["Java", "SQL", "JavaScript", "HTML5", "CSS3"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Smart Grid & IoT Software Intern",
    companyName: "Fluentgrid Limited",
    companyWebsite: "https://fluentgrid.com",
    location: "Visakhapatnam, Andhra Pradesh, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://fluentgrid.com/careers/",
    externalId: "intern-vizag-fluentgrid-01",
    description: "Verified smart utility software internship at Fluentgrid (Rushikonda IT Park, Vizag). Work on smart grid telemetry, metering data management, and enterprise software.",
    rawRequirements: "Proficiency in Java, Spring Framework, PostgreSQL/Oracle, and IoT communications.",
    skills: ["Java", "Spring Boot", "PostgreSQL", "IoT", "Microservices"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Cloud & Full Stack Intern",
    companyName: "Miracle Software Systems",
    companyWebsite: "https://www.miraclesoft.com",
    location: "Visakhapatnam, Andhra Pradesh, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹26,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.miraclesoft.com/careers/",
    externalId: "intern-vizag-miracle-01",
    description: "Verified enterprise cloud internship at Miracle Software Systems (Miracle City, Vizag). Build cloud-native web applications with React, Node.js, and AWS.",
    rawRequirements: "Experience in JavaScript, React, Node.js, REST APIs, and basic understanding of AWS services.",
    skills: ["React", "Node.js", "AWS", "MongoDB", "JavaScript"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Railway Signaling & IoT Embedded Intern",
    companyName: "Efftronics Systems",
    companyWebsite: "https://www.efftronics.com",
    location: "Vijayawada, Andhra Pradesh, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹28,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.efftronics.com/careers",
    externalId: "intern-vijayawada-efftronics-01",
    description: "Verified IoT & embedded systems internship at Efftronics Systems (Vijayawada). Design mission-critical railway automation, predictive maintenance, and data acquisition hardware.",
    rawRequirements: "Strong fundamentals in Embedded C, microcontrollers, communication protocols, and Python data logging.",
    skills: ["Embedded C", "Microcontrollers", "IoT", "Python", "Sensors"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Software Engineering Intern",
    companyName: "Zoho Corporation",
    companyWebsite: "https://www.zoho.com",
    location: "Tirupati, Andhra Pradesh, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹25,000 - ₹35,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.zoho.com/careers/",
    externalId: "intern-tirupati-zoho-01",
    description: "Verified software product development internship at Zoho Tirupati Development Centre. Build modular SaaS products, distributed databases, and high-performance web frontends.",
    rawRequirements: "Strong problem solving, data structures, Java or C++, clean algorithmic thinking, and web fundamentals.",
    skills: ["Java", "C++", "Data Structures", "Algorithms", "JavaScript"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "GIS & Software Application Intern",
    companyName: "Cyient",
    companyWebsite: "https://www.cyient.com",
    location: "Kakinada, Andhra Pradesh, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹16,000 - ₹24,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.cyient.com/careers/",
    externalId: "intern-kakinada-cyient-01",
    description: "Verified geospatial engineering & software internship at Cyient (Kakinada Development Centre). Build spatial data analytics, mapping pipelines, and Python automations.",
    rawRequirements: "Familiarity with Python, SQL, GIS concepts, spatial databases, and web frameworks.",
    skills: ["Python", "SQL", "GIS", "Data Analytics", "Git"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },

  // ==========================================
  // BATCH 10: TAMIL NADU & KERALA
  // ==========================================
  {
    title: "Product Engineering Intern (SaaS / React & Node)",
    companyName: "Freshworks",
    companyWebsite: "https://www.freshworks.com",
    location: "Chennai, Tamil Nadu, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹40,000 - ₹60,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.freshworks.com/company/careers/",
    externalId: "intern-chennai-freshworks-01",
    description: "Verified product development internship at Freshworks Global Hub (Chennai). Contribute to AI-powered customer service bots, cloud microservices, and high-performance UI components.",
    rawRequirements: "Solid foundations in JavaScript, React, Ruby/Node.js, REST APIs, and database fundamentals.",
    skills: ["React", "Node.js", "JavaScript", "PostgreSQL", "REST APIs"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "FinTech Platform Engineering Intern",
    companyName: "Chargebee",
    companyWebsite: "https://www.chargebee.com",
    location: "Chennai, Tamil Nadu, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹35,000 - ₹50,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.chargebee.com/careers/",
    externalId: "intern-chennai-chargebee-01",
    description: "Verified fintech software internship at Chargebee (Chennai). Build recurring billing microservices, global payment gateway connectors, and automated tax compliance engines.",
    rawRequirements: "Strong algorithmic foundations, Java, Spring Boot, MySQL, and distributed systems awareness.",
    skills: ["Java", "Spring Boot", "MySQL", "Distributed Systems", "Git"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Propulsion & Avionics Software Intern",
    companyName: "AgniKul Cosmos",
    companyWebsite: "https://agnikul.in",
    location: "Chennai, Tamil Nadu, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹30,000 - ₹45,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://agnikul.in/#/careers",
    externalId: "intern-chennai-agnikul-01",
    description: "Verified space launch vehicle software internship at AgniKul Cosmos (IIT Madras Research Park, Chennai). Develop flight simulation software, propulsion test control, and sensor telemetry.",
    rawRequirements: "Proficiency in C/C++, Python, numerical simulation, embedded Linux, and hardware-in-the-loop (HIL) testing.",
    skills: ["C++", "Python", "Linux", "Simulation", "Robotics"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Cloud Product Developer Intern",
    companyName: "Kovai.co",
    companyWebsite: "https://www.kovai.co",
    location: "Coimbatore, Tamil Nadu, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹32,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.kovai.co/careers",
    externalId: "intern-coimbatore-kovaico-01",
    description: "Verified enterprise SaaS development internship at Kovai.co (Coimbatore). Work on enterprise monitoring tools (Serverless360), knowledge base platforms (Document360), and Azure integrations.",
    rawRequirements: "Good understanding of C#, .NET, React or Angular, Microsoft Azure, and relational databases.",
    skills: [".NET", "C#", "Azure", "React", "SQL Server"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Healthcare Cloud Application Intern",
    companyName: "Solartis Technology",
    companyWebsite: "https://www.solartis.com",
    location: "Madurai, Tamil Nadu, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹25,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.solartis.com/careers/",
    externalId: "intern-madurai-solartis-01",
    description: "Verified insurance & cloud software internship at Solartis Technology (ELCOT IT Park, Madurai). Build microservices and cloud workflows with Java and React.",
    rawRequirements: "Foundational knowledge in Java, Spring Boot, REST APIs, HTML/CSS, and MySQL.",
    skills: ["Java", "Spring Boot", "React", "MySQL", "REST APIs"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Enterprise Digital Process Automation Intern",
    companyName: "Vuram (WNS)",
    companyWebsite: "https://www.vuram.com",
    location: "Tiruchirappalli, Tamil Nadu, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹28,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.vuram.com/careers/",
    externalId: "intern-trichy-vuram-01",
    description: "Verified low-code and digital transformation engineering internship at Vuram (Tiruchirappalli ELCOT IT Park). Develop hyperautomation and workflow automation pipelines.",
    rawRequirements: "Analytical thinking, database fundamentals, basic programming (Java/Python), and enthusiasm for enterprise software.",
    skills: ["Java", "Python", "SQL", "Process Automation", "Agile"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Software Intern",
    companyName: "UST Global",
    companyWebsite: "https://www.ust.com",
    location: "Thiruvananthapuram, Kerala, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹32,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.ust.com/careers",
    externalId: "intern-trivandrum-ust-01",
    description: "Verified digital software engineering internship at UST Global (Technopark, Thiruvananthapuram). Build enterprise cloud apps, microservices, and AI-assisted data pipelines.",
    rawRequirements: "Proficiency in Java or Python, React, relational databases, and modern cloud deployment basics.",
    skills: ["Java", "Python", "React", "PostgreSQL", "Docker"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Aviation & Logistics Software Intern",
    companyName: "IBS Software",
    companyWebsite: "https://www.ibsplc.com",
    location: "Thiruvananthapuram, Kerala, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹30,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.ibsplc.com/careers",
    externalId: "intern-trivandrum-ibs-01",
    description: "Verified airline & travel software internship at IBS Software (Technopark Phase III, Trivandrum). Develop mission-critical flight scheduling, passenger servicing, and revenue management platforms.",
    rawRequirements: "Strong Java/J2EE skills, Spring Framework, Oracle/PostgreSQL, and REST microservices.",
    skills: ["Java", "Spring Boot", "Oracle", "REST APIs", "Microservices"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Automotive Software & Autonomous Systems Intern",
    companyName: "Tata Elxsi",
    companyWebsite: "https://www.tataelxsi.com",
    location: "Thiruvananthapuram, Kerala, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹24,000 - ₹34,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.tataelxsi.com/careers",
    externalId: "intern-trivandrum-tataelxsi-01",
    description: "Verified automotive embedded systems internship at Tata Elxsi (Technopark, Trivandrum). Work on ADAS, connected vehicle telematics, AUTOSAR, and computer vision algorithms.",
    rawRequirements: "Solid foundations in C/C++, Embedded Linux, ROS, computer vision, and automotive protocols (CAN/LIN).",
    skills: ["C++", "C", "Embedded Linux", "Computer Vision", "ROS"],
    isGhostRisk: false,
    truthScore: 99,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Web & Cloud Intern",
    companyName: "QBurst",
    companyWebsite: "https://www.qburst.com",
    location: "Kochi, Kerala, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹28,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.qburst.com/company/career/",
    externalId: "intern-kochi-qburst-01",
    description: "Verified digital product engineering internship at QBurst (Infopark, Kochi). Develop modern web applications, mobile frontends, and REST APIs using Python/Node.js and React/Angular.",
    rawRequirements: "Proficiency in JavaScript/TypeScript, React or Angular, Node.js or Python, and Git.",
    skills: ["React", "TypeScript", "Node.js", "Python", "MongoDB"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Product Engineering & Microservices Intern",
    companyName: "KeyValue Systems",
    companyWebsite: "https://keyvalue.systems",
    location: "Kochi, Kerala, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹35,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://keyvalue.systems/careers",
    externalId: "intern-kochi-keyvalue-01",
    description: "Verified software product development internship at KeyValue Systems (Infopark, Kochi). Build high-throughput web applications for Silicon Valley and Indian hyper-growth startups.",
    rawRequirements: "Strong coding skills in React, Node.js, Go or Python, PostgreSQL, and modern cloud deployment.",
    skills: ["React", "Node.js", "Go", "PostgreSQL", "Docker"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Open Source Software Developer Intern",
    companyName: "Infinite Open Source Solutions",
    companyWebsite: "https://ioss.in",
    location: "Kozhikode, Kerala, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹15,000 - ₹22,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://ioss.in/careers/",
    externalId: "intern-calicut-ioss-01",
    description: "Verified web application development internship at Infinite Open Source Solutions (Cyberpark, Kozhikode). Build web portals, enterprise CRM extensions, and cloud backends.",
    rawRequirements: "Hands-on experience in PHP/Laravel or Python/Django, MySQL, Vue.js or React, and REST APIs.",
    skills: ["PHP", "Laravel", "Python", "MySQL", "React"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },

  // ==========================================
  // NORTHERN, CENTRAL & EASTERN HUBS
  // ==========================================
  {
    title: "AI Development & Frontend Engineering Intern",
    companyName: "Grazitti Interactive",
    companyWebsite: "https://www.grazitti.com",
    location: "Panchkula, Haryana, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹26,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.grazitti.com/company/careers/job-listing/",
    externalId: "intern-panchkula-grazitti-01",
    description: "Verified digital product engineering internship at Grazitti Interactive (Panchkula / Mohali). Work on Salesforce integrations, generative AI tools, and React frontends.",
    rawRequirements: "Knowledge of JavaScript, React, Python, REST APIs, and basic understanding of cloud systems.",
    skills: ["React", "JavaScript", "Python", "Salesforce", "REST APIs"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Game Development & Unity3D Intern",
    companyName: "ChicMic",
    companyWebsite: "https://www.chicmic.in",
    location: "Mohali, Punjab, India",
    workMode: WorkMode.ON_SITE,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹16,000 - ₹24,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.chicmic.in/careers/",
    externalId: "intern-mohali-chicmic-01",
    description: "Verified game engineering internship at ChicMic (IT Park, Mohali). Develop 2D/3D mobile games, game physics, and gameplay mechanics using Unity and C#.",
    rawRequirements: "Proficiency in C#, Unity 3D engine, game math/physics, and mobile game asset pipelines.",
    skills: ["C#", "Unity 3D", "Game Development", "Mobile Games", "Git"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "AI & Machine Learning Engineering Intern",
    companyName: "Evon Technologies",
    companyWebsite: "https://www.evontech.com",
    location: "Dehradun, Uttarakhand, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹25,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.evontech.com/careers.html",
    externalId: "intern-dehradun-evon-01",
    description: "Verified AI engineering internship at Evon Technologies (IT Park, Dehradun). Build computer vision algorithms, NLP document processors, and machine learning pipelines.",
    rawRequirements: "Strong coding skills in Python, PyTorch/TensorFlow, OpenCV, and data structures.",
    skills: ["Python", "Machine Learning", "PyTorch", "OpenCV", "SQL"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Data Engineering & Analytics Intern",
    companyName: "Impetus Technologies",
    companyWebsite: "https://www.impetus.com",
    location: "Indore, Madhya Pradesh, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹22,000 - ₹32,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.impetus.com/careers/",
    externalId: "intern-indore-impetus-01",
    description: "Verified big data software internship at Impetus Technologies (Super Corridor, Indore). Work on Apache Spark data processing, cloud warehouses (Snowflake/BigQuery), and Python ETL.",
    rawRequirements: "Strong foundations in Java/Python, SQL, Apache Spark, and distributed computing principles.",
    skills: ["Python", "Apache Spark", "SQL", "BigQuery", "Snowflake"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Full Stack Web Developer Intern",
    companyName: "Simform",
    companyWebsite: "https://www.simform.com",
    location: "Ahmedabad, Gujarat, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹20,000 - ₹28,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.simform.com/careers/",
    externalId: "intern-ahmedabad-simform-01",
    description: "Verified product engineering internship at Simform (Ahmedabad). Build cloud-native web applications with React, Node.js, AWS serverless, and GraphQL.",
    rawRequirements: "Knowledge of TypeScript, React, Node.js, Express, MongoDB, and AWS basics.",
    skills: ["TypeScript", "React", "Node.js", "AWS", "GraphQL"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "Software Engineering Intern",
    companyName: "GirnarSoft (CarDekho)",
    companyWebsite: "https://www.girnarsoft.com",
    location: "Jaipur, Rajasthan, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹25,000 - ₹35,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.girnarsoft.com/careers",
    externalId: "intern-jaipur-girnarsoft-01",
    description: "Verified auto-tech software internship at GirnarSoft / CarDekho (Jaipur). Work on high-traffic consumer web portals, recommendation engines, and microservices.",
    rawRequirements: "Solid foundations in Python/PHP/Node.js, MySQL, React, and REST microservices.",
    skills: ["Python", "Node.js", "React", "MySQL", "REST APIs"],
    isGhostRisk: false,
    truthScore: 98,
    publishedAt: new Date().toISOString(),
  },
  {
    title: "GovTech & Cloud Systems Intern",
    companyName: "CSM Technologies",
    companyWebsite: "https://www.csm.tech",
    location: "Bhubaneswar, Odisha, India",
    workMode: WorkMode.HYBRID,
    jobType: JobType.INTERNSHIP,
    salaryOrStipend: "₹18,000 - ₹25,000 / month (Stipend)",
    experienceYears: 0,
    source: "EXTERNAL",
    sourceUrl: "https://www.csm.tech/careers",
    externalId: "intern-bhubaneswar-csm-01",
    description: "Verified enterprise software internship at CSM Technologies (Infocity, Bhubaneswar). Develop digital governance platforms, citizen service portals, and cloud backends.",
    rawRequirements: "Proficiency in Java or C#, relational databases (PostgreSQL/SQL Server), and web UI fundamentals.",
    skills: ["Java", ".NET Core", "PostgreSQL", "React", "REST APIs"],
    isGhostRisk: false,
    truthScore: 97,
    publishedAt: new Date().toISOString(),
  },
];
